<a href="https://colab.research.google.com/github/lunecarvalho/newslens-development/blob/main/02_topic_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/cleaned_dataset.csv')

print(f'Total de registros: {len(df)}')
df.head()

Total de registros: 7199

,id,label,arquivo,texto_original,texto_preprocessado,tema
0,1,falso,1170.txt,Falso médico é preso pela PM de Santa Catarina...,falso médico é preso pela pm de santa catarina...,NaN
1,2,falso,1688.txt,Antes da confirmação da morte de Teori Zavasck...,antes da confirmação da morte de teori zavasck...,NaN
2,3,falso,1863.txt,Senador que assume o lugar de Renan foi flagra...,senador que assume o lugar de renan foi flagra...,NaN
3,4,falso,1563.txt,"Repórter relata conversa entre deputados: ""A D...",repórter relata conversa entre deputados: a di...,NaN
4,5,falso,3556.txt,Governo repressor e comunista usa exército par...,governo repressor e comunista usa exército par...,NaN

In [5]:
print('Textos vazios:')
print((df['texto_preprocessado'].fillna('').str.strip() == '').sum())

Textos vazios:
0

In [6]:
df['tamanho_texto'] = df['texto_preprocessado'].str.len()

df['tamanho_texto'].describe()

count     7199.000000
mean      1103.320878
std        697.240864
min         46.000000
25%        694.000000
50%        946.000000
75%       1340.000000
max      12472.000000
Name: tamanho_texto, dtype: float64

In [7]:
df.drop(columns=['tamanho_texto'], inplace=True)

In [8]:
print('Textos duplicados:', df['texto_preprocessado'].duplicated().sum())

Textos duplicados: 0

In [9]:
!pip install bertopic

Requirement already satisfied: bertopic in /usr/local/lib/python3.13/dist-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (2.1.3)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.13/dist-packages (from bertopic) (2.2.3)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.13/dist-packages (from bertopic) (5.7.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.13/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.44.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.13/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.13/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly>=4.7.0->bertopic) (26.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.15.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.27.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.16.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.13/dist-packages (from umap-learn>=0.5.0->bertopic) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.13/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)

In [10]:
documentos = df['texto_preprocessado'].fillna('').tolist()

print(f'Total de documentos: {len(documentos)}')

Total de documentos: 7199

In [11]:
print(documentos[0])

falso médico é preso pela pm de santa catarina: sou formado em medicina pelo seriado greys anatomy. josias de farias júnior se passava por médico em um hospital da unimed em balneário camboriú, santa catarina. o estelionatário de 19 anos foi preso pela polícia na noite da última terça-feira (30). ele portava prontuários, carimbos médicos, um jaleco e um estetoscópio que, de acordo com testemunhas, foram roubados de um médico do próprio hospital. seguranças do local desconfiaram da credencial do jovem e o detiveram até a chegada da polícia. ainda não se sabe se ele chegou a atender algum paciente ou até mesmo prescreveu alguma receita. durante o depoimento, ele afirmou ser fã de um seriado de tv (sobre medicina) muito famoso nos eua: greys anatomy. em um vídeo postado nas redes sociais ( minuto 0:52 ) josias declara ser um fã apaixonado das séries greys anatomy e bones.

In [12]:
for i in range(3):
    print(f'\nDOCUMENTO {i + 1}:')
    print(documentos[i][:500])

DOCUMENTO 1:
falso médico é preso pela pm de santa catarina: sou formado em medicina pelo seriado greys anatomy. josias de farias júnior se passava por médico em um hospital da unimed em balneário camboriú, santa catarina. o estelionatário de 19 anos foi preso pela polícia na noite da última terça-feira (30). ele portava prontuários, carimbos médicos, um jaleco e um estetoscópio que, de acordo com testemunhas, foram roubados de um médico do próprio hospital. seguranças do local desconfiaram da credencial do

DOCUMENTO 2:
antes da confirmação da morte de teori zavascki, senador postou mensagem estranha no twitter. senador disse que o jornal nacional iria lançar uma bomba sobre o brasil. será uma infeliz coincidência? uma mensagem enigmática foi postada pelo senador josé medeiros (psdmt) pouco antes da confirmação da morte do ministro teori zavascki: não vou antecipar furo porque não sou jornalista mas o jornal nacional hj trará uma bomba de forte impacto no brasil, envolvendo stf. ( 16: 58 19 jan 2017 brasília, b

DOCUMENTO 3:
senador que assume o lugar de renan foi flagrado chamando sérgio moro e delegados da pf de bandidos. após o afastamento de renan calheiros (pmdb-al) da presidência do senado, quem assume temporariamente o cargo é jorge viana (pt-ac). renan foi afastado ontem (06) pelo ministro marco aurélio mello (stf) que decidiu acatar uma ação cautelar impetrada pelo partido rede. a decisão ainda deverá ser votada pelo plenário da corte, que ainda não marcou data para o julgamento. o senador petista apareceu

In [13]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (5.7.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (5.15.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (0.22.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.27.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (2.1.3)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

In [14]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    'paraphrase-multilingual-MiniLM-L12-v2'
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [15]:
embeddings = embedding_model.encode(
    documentos,
    show_progress_bar=True
)

print(embeddings.shape)

Batches:   0%|          | 0/225 [00:00<?, ?it/s]

(7199, 384)

In [16]:
!pip install bertopic umap-learn hdbscan

Requirement already satisfied: bertopic in /usr/local/lib/python3.13/dist-packages (0.17.4)
Requirement already satisfied: umap-learn in /usr/local/lib/python3.13/dist-packages (0.5.12)
Requirement already satisfied: hdbscan in /usr/local/lib/python3.13/dist-packages (0.8.44)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (2.1.3)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.13/dist-packages (from bertopic) (2.2.3)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.13/dist-packages (from bertopic) (5.7.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.13/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.44.0)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.13/dist-packages (from hdbscan) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly>=4.7.0->bertopic) (26.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.15.0)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.27.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.32.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)

In [17]:
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN

In [18]:
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)

In [19]:
hdbscan_model = HDBSCAN(
    min_cluster_size=15,
    min_samples=5,
    metric='euclidean',
    cluster_selection_method='eom',
    prediction_data=True
)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    ngram_range=(1, 2),
    min_df=1,
    max_df=1.0
)

In [21]:
topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    language='multilingual',
    verbose=True
)

In [22]:
topics, probabilities = topic_model.fit_transform(
    documentos,
    embeddings
)

2026-08-27 12:10:46,927 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-27 12:11:54,901 - BERTopic - Dimensionality - Completed ✓
2026-08-27 12:11:54,904 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-27 12:11:55,234 - BERTopic - Cluster - Completed ✓
2026-08-27 12:11:55,241 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-27 12:12:02,081 - BERTopic - Representation - Completed ✓

In [23]:
topic_info = topic_model.get_topic_info()

topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2647,-1_de_que_do_da,"[de, que, do, da, em, para, no, um, na, com]",[atualizada às 12h07 o senador delcídio amaral...
1,0,363,0_brasil_que_de_do,"[brasil, que, de, do, um, da, em, não, para, no]",[lula nunca foi modesto. já se comparou a jesu...
2,1,346,1_norte_coreia_do norte_coreia do,"[norte, coreia, do norte, coreia do, kim, eua,...",[coreia do norte lança míssil no litoral japon...
3,2,266,2_de_para_bilhões_em,"[de, para, bilhões, em, do, que, da, com, no, ...",[veio para confundir incerteza sobre reais int...
4,3,261,3_milhões_odebrecht_de_da,"[milhões, odebrecht, de, da, que, em, dinheiro...",[baiano entrega documentos à pf que comprovam ...
...,...,...,...,...,...
70,69,16,69_internet_banda larga_larga_hackers,"[internet, banda larga, larga, hackers, que, d...",[internet limitada: 12 horas de netflix ou alg...
71,70,15,70_aplicativos_uber_caminhoneiros_transporte,"[aplicativos, uber, caminhoneiros, transporte,...",[prefeitura de sp flexibiliza futuras regras p...
72,71,15,71_pf_da pf_diretor geral_daiello,"[pf, da pf, diretor geral, daiello, diretor, n...",[delegado fernando segóvia assumirá comando da...
73,72,15,72_prefeito_doria_vereadores_crivella,"[prefeito, doria, vereadores, crivella, promes...",[doria deixa promessas de campanha de fora do ...
74,73,15,73_aposentadoria_idade_reforma_previdência,"[aposentadoria, idade, reforma, previdência, i...","[segunda-feira, 5 de fevereiro de 2018. boa no..."

In [24]:
print(f'Quantidade de tópicos: {len(topic_info) - 1}')

Quantidade de tópicos: 74

In [25]:
topic_info.head(15)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2647,-1_de_que_do_da,"[de, que, do, da, em, para, no, um, na, com]",[atualizada às 12h07 o senador delcídio amaral...
1,0,363,0_brasil_que_de_do,"[brasil, que, de, do, um, da, em, não, para, no]",[lula nunca foi modesto. já se comparou a jesu...
2,1,346,1_norte_coreia_do norte_coreia do,"[norte, coreia, do norte, coreia do, kim, eua,...",[coreia do norte lança míssil no litoral japon...
3,2,266,2_de_para_bilhões_em,"[de, para, bilhões, em, do, que, da, com, no, ...",[veio para confundir incerteza sobre reais int...
4,3,261,3_milhões_odebrecht_de_da,"[milhões, odebrecht, de, da, que, em, dinheiro...",[baiano entrega documentos à pf que comprovam ...
5,4,203,4_dilma_impeachment_presidente_que,"[dilma, impeachment, presidente, que, do, de, ...",[manter o discurso de golpe é impróprio ao paí...
6,5,188,5_stf_supremo_ministro_do,"[stf, supremo, ministro, do, mendes, gilmar, t...",[fachin envia à primeira instância denúncia co...
7,6,181,6_lula_ex_ex presidente_moro,"[lula, ex, ex presidente, moro, da, do, de, de...",[condenação de lula na 2ª instância: veja as p...
8,7,146,7_candidato_alckmin_partido_psdb,"[candidato, alckmin, partido, psdb, bolsonaro,...","[em evento com alckmin e doria, fhc defende pr..."
9,8,138,8_igreja_pastor_que_de,"[igreja, pastor, que, de, um, uma, deus, da ig...",[pastor que anda de ferrari se pronuncia: o ca...
10,9,137,9_anos_de_mãe_que,"[anos, de, mãe, que, em, foi, na, um, da, uma]",[suspeita de matar e retirar bebê de grávida d...
11,10,107,10_avião_aeronave_acidente_de,"[avião, aeronave, acidente, de, piloto, do, ae...",[dono da learjet diz que atentado às torres gê...
12,11,104,11_prisão_de_da_preso,"[prisão, de, da, preso, na, em, ex, pf, do, foi]",[ex-ministro henrique eduardo alves é preso em...
13,12,94,12_manifestantes_do_de_da,"[manifestantes, do, de, da, em, ato, protesto,...",[ato contra temer em brasília tem confronto; p...
14,13,79,13_lula_que_não_se,"[lula, que, não, se, de, um, do, ele, dilma, p...",[jornalista dá bronca em dilma: se pedir pra e...

In [26]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [27]:
from nltk.corpus import stopwords

stopwords_pt = stopwords.words('portuguese')

print(stopwords_pt[:20])

['a', 'à', 'ao', 'aos', 'aquela', 'aquelas', 'aquele', 'aqueles', 'aquilo', 'as', 'às', 'até', 'com', 'como', 'da', 'das', 'de', 'dela', 'delas', 'dele']

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    stop_words=stopwords_pt,
    ngram_range=(1, 2),
    min_df=1
)

In [29]:
topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    language='multilingual',
    verbose=True
)

In [30]:
topics, probabilities = topic_model.fit_transform(
    documentos,
    embeddings
)

2026-08-27 12:12:04,888 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-27 12:12:23,429 - BERTopic - Dimensionality - Completed ✓
2026-08-27 12:12:23,430 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-27 12:12:24,017 - BERTopic - Cluster - Completed ✓
2026-08-27 12:12:24,024 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-27 12:12:29,946 - BERTopic - Representation - Completed ✓

In [31]:
topic_info = topic_model.get_topic_info()

topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2647,-1_lula_presidente_ex_federal,"[lula, presidente, ex, federal, ex presidente,...",[atualizada às 12h07 o senador delcídio amaral...
1,0,363,0_brasil_país_presidente_lula,"[brasil, país, presidente, lula, brasileiros, ...",[a defesa de aécio neves exigiu que o stf afas...
2,1,346,1_norte_coreia_coreia norte_kim,"[norte, coreia, coreia norte, kim, eua, nuclea...",[coreia do norte alerta países: não se juntem ...
3,2,266,2_bilhões_governo_ano_milhões,"[bilhões, governo, ano, milhões, 2017, trabalh...",[saiba como foi a semana na economia. redução ...
4,3,261,3_odebrecht_milhões_dinheiro_delação,"[odebrecht, milhões, dinheiro, delação, ex, pr...",[delação de ex-diretor da odebrecht atinge tem...
...,...,...,...,...,...
70,69,16,69_internet_banda larga_larga_hackers,"[internet, banda larga, larga, hackers, banda,...",[internet limitada: 12 horas de netflix ou alg...
71,70,15,70_aplicativos_uber_caminhoneiros_transporte,"[aplicativos, uber, caminhoneiros, transporte,...",[prefeitura de sp flexibiliza futuras regras p...
72,71,15,71_pf_diretor geral_daiello_diretor,"[pf, diretor geral, daiello, diretor, novo dir...",[delegado fernando segóvia assumirá comando da...
73,72,15,72_prefeito_doria_vereadores_crivella,"[prefeito, doria, vereadores, crivella, promes...",[doria deixa promessas de campanha de fora do ...
74,73,15,73_aposentadoria_idade_reforma_idade mínima,"[aposentadoria, idade, reforma, idade mínima, ...",[deputado chora ao comentar reforma da previdê...

In [32]:
print(topic_model.get_topic_info()[['Topic', 'Count', 'Name']].to_string(index=False))

 Topic  Count                                            Name
    -1   2647                   -1_lula_presidente_ex_federal
     0    363                   0_brasil_país_presidente_lula
     1    346                 1_norte_coreia_coreia norte_kim
     2    266                   2_bilhões_governo_ano_milhões
     3    261            3_odebrecht_milhões_dinheiro_delação
     4    203         4_dilma_impeachment_presidente_rousseff
     5    188                   5_stf_supremo_ministro_mendes
     6    181                    6_lula_ex presidente_moro_ex
     7    146                7_candidato_alckmin_partido_psdb
     8    138                       8_igreja_pastor_deus_papa
     9    137                           9_anos_mãe_jovem_bebê
    10    107               10_avião_aeronave_acidente_piloto
    11    104                           11_prisão_preso_pf_ex
    12     94           12_manifestantes_ato_protesto_polícia
    13     79                        13_lula_dilma_petista_pt
    14     78                       14_anos_morreu_ator_corpo
    15     72                   15_cantor_música_marrone_ator
    16     70               16_senador_lindbergh_senado_renan
    17     62             17_rio_segurança_intervenção_forças
    18     59      18_presos_detentos_presídios_penitenciária
    19     54         19_temer_presidente_michel_michel temer
    20     49                    20_síria_ataque_assad_rússia
    21     48           21_polícia federal_pf_federal_polícia
    22     48                     22_lava jato_lava_jato_lula
    23     48                    23_água_furacão_irma_mariana
    24     47                       24_vírus_zika_casos_febre
    25     46   25_maia_rodrigo maia_câmara_presidente câmara
    26     45                26_tse_chapa_cassação_julgamento
    27     45            27_festival_carnaval_teatro_salvador
    28     40           28_sírio libanês_sírio_libanês_médico
    29     39                      29_arte_nu_exposição_museu
    30     38                30_terra_planeta_nasa_cientistas
    31     37               31_senado_senadores_proposta_foro
    32     37             32_denúncia_câmara_deputados_contra
    33     36              33_olímpica_vila_vila olímpica_rio
    34     36             34_lula_ex presidente_presidente_ex
    35     34                  35_carne_fraca_carne fraca_brf
    36     34                 36_vereador_paulista_beto_vídeo
    37     33            37_futebol_corinthians_francês_clube
    38     32                      38_ator_zezé_mayer_assédio
    39     32        39_livro_literatura_shakespeare_escritor
    40     31                40_apartamento_lula_imóvel_sítio
    41     29              41_demissão_temer_ministro_palácio
    42     29            42_câncer_células_pacientes_pesquisa
    43     29               43_globo_vivo_emissora_rede globo
    44     28           44_mortes_mortos_homicídios_violência
    45     27             45_facebook_rede social_rede_social
    46     26                   46_vida_câncer_pessoas_muitas
    47     26                      47_lula_moro_depoimento_ex
    48     25 48_trump_donald_donald trump_presidente estados
    49     25             49_carro_acidente_motorista_veículo
    50     25                    50_fidel_cuba_castro_cubanos
    51     24                          51_lula_moro_defesa_ex
    52     24          52_violência_homicídios_brasil_pessoas
    53     24                    53_rússia_putin_russos_russo
    54     24                 54_ano_2017_fatos_retrospectiva
    55     23       55_renan_senado_calheiros_renan calheiros
    56     23                 56_triplex_guarujá_lula_solaris
    57     22            57_tiririca_deputado_câmara_discurso
    58     21      58_educação_ensino_universidade_estudantes
    59     20            59_reforma_temer_previdência_governo
    60     20         60_dilma_rousseff_dilma rousseff_brasil
    61     19             61_palocci_odebrecht_ex_ex ministro
    62     18      62_jornalista_jornalistas_reinaldo_boechat
    63     18               63_nacionalismo_bauman_mundo_ódio
    64     17        64_passaporte_lula_federal_passaporte ex
    65     17              65_aécio_neves_aécio neves_senador
    66     17                  66_cão_cachorro_animais_animal
    67     17              67_pessoas_atentado_ataque_londres
    68     16           68_hospital_internado_passa bem_passa
    69     16           69_internet_banda larga_larga_hackers
    70     15    70_aplicativos_uber_caminhoneiros_transporte
    71     15             71_pf_diretor geral_daiello_diretor
    72     15           72_prefeito_doria_vereadores_crivella
    73     15     73_aposentadoria_idade_reforma_idade mínima

In [33]:
print("Quantidade de tópicos:", len(topic_model.get_topic_info()) - 1)

Quantidade de tópicos: 74

In [34]:
topic_model.get_topic(0)

[('brasil', np.float64(0.013682024197759761)),
 ('país', np.float64(0.007358838691703302)),
 ('presidente', np.float64(0.006870159021953427)),
 ('lula', np.float64(0.0056173653802873745)),
 ('brasileiros', np.float64(0.005185127281866319)),
 ('brasileiro', np.float64(0.004910664251309181)),
 ('temer', np.float64(0.004898818470295437)),
 ('política', np.float64(0.00470586834950469)),
 ('governo', np.float64(0.00449558909555325)),
 ('brasileira', np.float64(0.004402832896259538))]

In [35]:
topic_model.get_topic(1)

[('norte', np.float64(0.03685486679427854)),
 ('coreia', np.float64(0.03114385811602478)),
 ('coreia norte', np.float64(0.02334043602889135)),
 ('kim', np.float64(0.02001704431130594)),
 ('eua', np.float64(0.019487603839474326)),
 ('nuclear', np.float64(0.015916850518809658)),
 ('un', np.float64(0.015397884620307289)),
 ('trump', np.float64(0.015143009660840973)),
 ('coréia', np.float64(0.014152831766273345)),
 ('sul', np.float64(0.013613721947014122))]

In [36]:
topic_info = topic_model.get_topic_info()

print(
    topic_info[['Topic', 'Count', 'Name']]
    .to_string(index=False)
)

 Topic  Count                                            Name
    -1   2647                   -1_lula_presidente_ex_federal
     0    363                   0_brasil_país_presidente_lula
     1    346                 1_norte_coreia_coreia norte_kim
     2    266                   2_bilhões_governo_ano_milhões
     3    261            3_odebrecht_milhões_dinheiro_delação
     4    203         4_dilma_impeachment_presidente_rousseff
     5    188                   5_stf_supremo_ministro_mendes
     6    181                    6_lula_ex presidente_moro_ex
     7    146                7_candidato_alckmin_partido_psdb
     8    138                       8_igreja_pastor_deus_papa
     9    137                           9_anos_mãe_jovem_bebê
    10    107               10_avião_aeronave_acidente_piloto
    11    104                           11_prisão_preso_pf_ex
    12     94           12_manifestantes_ato_protesto_polícia
    13     79                        13_lula_dilma_petista_pt
    14     78                       14_anos_morreu_ator_corpo
    15     72                   15_cantor_música_marrone_ator
    16     70               16_senador_lindbergh_senado_renan
    17     62             17_rio_segurança_intervenção_forças
    18     59      18_presos_detentos_presídios_penitenciária
    19     54         19_temer_presidente_michel_michel temer
    20     49                    20_síria_ataque_assad_rússia
    21     48           21_polícia federal_pf_federal_polícia
    22     48                     22_lava jato_lava_jato_lula
    23     48                    23_água_furacão_irma_mariana
    24     47                       24_vírus_zika_casos_febre
    25     46   25_maia_rodrigo maia_câmara_presidente câmara
    26     45                26_tse_chapa_cassação_julgamento
    27     45            27_festival_carnaval_teatro_salvador
    28     40           28_sírio libanês_sírio_libanês_médico
    29     39                      29_arte_nu_exposição_museu
    30     38                30_terra_planeta_nasa_cientistas
    31     37               31_senado_senadores_proposta_foro
    32     37             32_denúncia_câmara_deputados_contra
    33     36              33_olímpica_vila_vila olímpica_rio
    34     36             34_lula_ex presidente_presidente_ex
    35     34                  35_carne_fraca_carne fraca_brf
    36     34                 36_vereador_paulista_beto_vídeo
    37     33            37_futebol_corinthians_francês_clube
    38     32                      38_ator_zezé_mayer_assédio
    39     32        39_livro_literatura_shakespeare_escritor
    40     31                40_apartamento_lula_imóvel_sítio
    41     29              41_demissão_temer_ministro_palácio
    42     29            42_câncer_células_pacientes_pesquisa
    43     29               43_globo_vivo_emissora_rede globo
    44     28           44_mortes_mortos_homicídios_violência
    45     27             45_facebook_rede social_rede_social
    46     26                   46_vida_câncer_pessoas_muitas
    47     26                      47_lula_moro_depoimento_ex
    48     25 48_trump_donald_donald trump_presidente estados
    49     25             49_carro_acidente_motorista_veículo
    50     25                    50_fidel_cuba_castro_cubanos
    51     24                          51_lula_moro_defesa_ex
    52     24          52_violência_homicídios_brasil_pessoas
    53     24                    53_rússia_putin_russos_russo
    54     24                 54_ano_2017_fatos_retrospectiva
    55     23       55_renan_senado_calheiros_renan calheiros
    56     23                 56_triplex_guarujá_lula_solaris
    57     22            57_tiririca_deputado_câmara_discurso
    58     21      58_educação_ensino_universidade_estudantes
    59     20            59_reforma_temer_previdência_governo
    60     20         60_dilma_rousseff_dilma rousseff_brasil
    61     19             61_palocci_odebrecht_ex_ex ministro
    62     18      62_jornalista_jornalistas_reinaldo_boechat
    63     18               63_nacionalismo_bauman_mundo_ódio
    64     17        64_passaporte_lula_federal_passaporte ex
    65     17              65_aécio_neves_aécio neves_senador
    66     17                  66_cão_cachorro_animais_animal
    67     17              67_pessoas_atentado_ataque_londres
    68     16           68_hospital_internado_passa bem_passa
    69     16           69_internet_banda larga_larga_hackers
    70     15    70_aplicativos_uber_caminhoneiros_transporte
    71     15             71_pf_diretor geral_daiello_diretor
    72     15           72_prefeito_doria_vereadores_crivella
    73     15     73_aposentadoria_idade_reforma_idade mínima

In [37]:
topic_model.visualize_topics()

In [38]:
topic_model.visualize_barchart(top_n_topics=20)

In [42]:
topic_model.get_representative_docs(0)

['a defesa de aécio neves exigiu que o stf afaste edson fachin da relatoria do processo que o afasta do senado. nunca o samba do crioulo doido foi tão atual como no brasil hoje, como lembra eliane cantanhêde na coluna no estadão. nesta nau dos insensatos, a defesa escolhe o juiz de acordo com as conveniências do réu e o fato de ele já ter delinquido em outra ocasião o autoriza a fazê-lo. quanto mais diversas forem as causas contra o acusado mais ele se acha no direito de se livrar de quem o condenou antes e procurar quem tradicionalmente o liberta, caso dos tucanos que sempre buscam e conseguem cair nas mãos generosas de gilmar mendes e alexandre de moraes e longe de juízes mais rigorosos como fachin. (comentário no jornal eldorado da rádio eldorado fm 107,3 na terça-feira 3 de outubro de 2017, às 7h30m) para ouvir clique aqui e, em seguida, no play para ouvir o samba do crioulo doido com os demônios da garoa clique aqui abaixo, a degravação do comentário na íntegra: eldorado, 3 de outubro de 2017, terça-feira sonora 0310 eunício sonora samba do crioulo doido os demônios da garoa começar do começo o ministro edson fachin, do supremo tribunal federal (stf), decidiu encaminhar à presidente do stf, ministra cármen lúcia, o pedido da defesa do senador aécio neves (psdb-mg) para que o mandado de segurança impetrado pelo tucano seja redistribuído para outro relator. virou moda trocar relator no stf a pedido da defesa? o mandado de segurança foi originalmente distribuído para o ministro edson fachin, relator do caso jf. para a defesa de aécio, fachin não poderia ser o relator do mandado de segurança, porque que se questiona no processo justamente o restabelecimento de medidas cautelares que haviam sido determinadas pelo próprio fachin em maio deste ano. cabe agora à presidente do stf decidir se redistribui ou não o processo. não há previsão de quando isso vai ocorrer. os cinco ministros da primeira turma do stf luís roberto barroso, rosa weber, luiz fux, alexandre de moraes e marco aurélio mello foram excluídos do sorteio eletrônico que definiu a relatoria do mandado de segurança, já que a defesa de aécio pretende suspender a decisão desse colegiado, que afastou aécio das funções parlamentares na semana passada. o sorteio eletrônico, então, envolveu apenas os ministros da segunda turma: fachin, ricardo lewandowski, gilmar mendes, dias toffoli e o decano da corte, celso de mello. cármen lúcia ficou de fora desse sorteio por não receber esse tipo de ação durante o exercício da presidência do tribunal. o tucano quer que a determinação da primeira turma seja suspensa até que o plenário da corte julgue uma ação direta de inconstitucionalidade que trata sobre o afastamento de parlamentares. a discussão dessa matéria está marcada para o dia 11 de outubro. em maio, quando a delação da jf veio à tona, fachin determinou o afastamento de aécio neves das funções parlamentares ou de de qualquer outra função pública. também impôs à época duas medidas cautelares ao tucano: a proibição de contatar qualquer outro investigado ou réu no conjunto de fatos revelados na delação da jf e a proibição de se ausentar do país, devendo entregar seu passaporte. as medidas determinadas por fachin foram derrubadas pelo ministro marco aurélio mello em junho. na semana passada, no entanto, a primeira turma do stf decidiu não apenas restabelecê-las como colocou aécio em recolhimento domiciliar noturno. a decisão impugnada por meio do presente ms restabelece as medidas cautelares originariamente impostas por ato de vossa excelência. dito de outra maneira, vossa excelência não pode, data venia, ser relator do mandamus que impugna justamente o ato por si praticado, nos termos expressos do art. 67, 8º, do ristf. diante do exposto, requer-se a imediata e livre redistribuição do feito entre um dos demais ministros componentes da col. 2ª turma, sustenta o advogado alberto zacharias toron, defensor de aécio. nunca o samba do crioulo doido foi tão atual como no brasil de hoje. nesta nau dos insensatos, a defesa escolhe o juiz de acordo com as conveniências do réu e o fato de ele já ter delinqüido em outra ocasião o autoriza a fazê-lo. quanto mais diversas forem as causas contra o acusado mais ele se acha no direito de se livrar de quem o condenou antes e procurar quem tradicionalmente o liberta, caso dos tucanos que sempre buscam e conseguem cair nas mãos generosas de gilmar mendes e alexandre de moraes e longe de juízes mais rigorosos como fachin. foi assim que jacob barata conseguiu livrar-se da juíza sorteada, rosa weber, e cair no colo de gilmar, que lhe deu habeas corpus. sonora 0310 eunício o juiz federal sérgio moro determinou ontem que o hospital sírio-libanês informe se o advogado roberto teixeira, compadre do ex-presidente lula, e o contador joão muniz leite estiveram no local atendendo a glaucos da costamarques, que informa ter assinado os recibos no mesmo dia a pedido do compadre',
 'temer pode entregar o poder aos militares após renuncia. temer está em constante contato com os comandantes das forças armadas nos últimos dias. durante as manifestações em brasília os atos de vandalismos mostraram ao brasil o que podem vir a ser os dias após o impeachment. acossado por denúncias de delatores da jf na lava jato, o presidente michel temer manteve uma reunião com o ministro da defesa, raul jungmann, e os três comandantes das forças armadas: aeronáutica, marinha e exército. muitos assessores do presidente se questionaram sobre o porquê do encontro de temer com os militares num instante em que a crise era política, sobretudo. dada a desconfiança em relação ao encontro, uma manifestação oficial sobre a reunião só veio a público bem mais tarde. o comandante do exército, general villas bôas, tentou transmitir, por meio de nota, um clima de normalidade. afirmou, na ocasião, que a conjuntura atual foi discutida e que a atuação do exército tem por base os pilares da estabilidade, legalidade e legitimidade. cinco dias após o encontro, temer decidiu convocar as tropas federais para conter as manifestações contra seu governo. estas ações estão sendo interpretadas por analistas políticos como o início de uma transição de poder. diante do caótico quadro político, econômico e social que o brasil está vivendo o presidente michel temer está preocupado com o que poderia vir a acontecer com a realização de mais um impeachment. com um cenário de polarização política entre extrema direita e extrema esquerda o brasil pode viver uma verdadeira guerra civil. constitucionalmente a deposição de temer deveria ser seguida por uma eleição indireta que elegeria um novo presidente para comandar o brasil até 31 de dezembro de 2018. no entanto os militantes de esquerda já tentam emplacar um golpe constitucional ao irem as ruas pedir eleições diretas. o desespero da esquerda por eleições diretas em 2017 está intimamente relacionado com o crescimento de lula nas pesquisas eleitorais nos últimos meses. a mídia conseguiu o transformar o réu em vítima e a população está comovida pelo fato dele ter perdido a esposa e ter que prestar longo depoimento na lava jato. de fato, hoje o brasil corre sério risco de eleger lula pela terceira vez. com uma condenação em segunda instância lula estaria fora do jogo político de 2018 e sua militância pode ir ainda mais armada para as ruas para promover depredações e violências. aí está a possível missão das forças armadas. assumir o poder antes que o caos se estabeleça de vez no brasil. ao contrário de 1964 desta vez os militares não irão tirar o presidente a força. a justiça fará isso de forma democrática e as forças armadas farão a transição contendo os possíveis excessos de militantes da extrema esquerda eou direita. especula-se que o general hamilton mourão seja o escolhido para presidir o brasil durante o período 2017-2018. mourão é general de 4 estrelas, ainda na chefia do comando militar do sul, não é considerado bom opção nome por michel temer. mourão é hoje associado a movimentos anti-pt e intervencionistas. em algumas manifestações foram erguidas estátuas em sua homenagem.',
 'ciro gomes ataca bolsonaro, dória, dilma e lula. ciro gomes deu a entrevista mais bombástica dentre os pré-candidatos à presidência do brasil nas eleições 2018. não poupou nenhum de seus principais concorrentes e mostrou que nos debates será um dos mais provocativos presidenciáveis. o pré-candidato à presidência ciro gomes (pdt-ce) foi entrevistado nesta quarta-feira no programa pânico, da rádio jovem pan, e não poupou críticas a três possíveis concorrentes nas eleições de 2018: luiz inácio lula da silva (pt), jair bolsonaro (psc) e joão doria (psdb), além da ex-presidente dilma rouseff (pt). no início da entrevista, que teve mais de uma hora de duração, o presidenciável defende o fim da polarização entre os brasileiros para que os problemas possam ser superados. o brasil não pode cair na esparrela de aceitar essa falsa divisão entre coxinha e mortadela. tem que discutir o futuro. se a gente for transformar o embate que nós temos hoje nesse ódio ou paixão ao redor do lula, o brasil não sai de onde está. ao ser questionado pelos integrantes da bancada sobre a ovada recebida pelo pelo prefeito de são paulo, joão doria (psdb) durante uma visita a salvador na segunda-feira, ciro disse que a atitude do manifestante não foi normal nem civilizada, mas aproveitou para criticar o paulista. o doria, na posição de prefeito de são paulo, aperfeiçoa essa tragédia brasileira, porque é aquele político que não tem nada na cabeça e lê pesquisa com assessoria de marquetagem comercial. o que é que o marqueteiro está dizendo? tá todo mundo puto com os políticos, então ele é um não-político. todo mundo quer alguém que resolva os problemas, então ele é um gestor. e tá todo mundo zangadíssimo com a esculhambação que generalizou-se no pt, então ele é anti-pt, o anti-lula e é grosseiro isso não resolve nada. dilma ciro afirmou ter considerado o processo de impeachment um golpe, mas que não quer dizer que aprovasse o governo da petista. falar mal do governo da dilma é uma coisa quase covarde, porque é um governo desastrado. corrupta ela não é, tanto que nem sequer foi acusada. foi golpe porque governo corrupto você tem que provar funcionalmente o crime de responsabilidade dolosamente cometido pelo titular. e não aconteceu. eu vou ser presidente do brasil e ninguém vai me derrubar por protocolos formais. a dilma se deixou imolar porque não é do ramo. lula durante uma brincadeira entre os integrantes do programa sobre a melhor escolha no caso de um segundo turno entre lula e bolsonaro, ciro respondeu: eu tapo o nariz e voto no lula. em outro momento da entrevista, ele diz que lula entregou furnas ao ex-deputado federal eduardo cunha (pmdb-rj) e que, em razão de sua popularidade. brincou de deus ao escolher michel temer (pmdb) como vice de dilma rousseff na chapa presidencial de 2014. bolsonaro embora ciro tenha reforçado ao longo da entrevista que respeita e tem uma boa relação com jair bolsonaro, ele diz considerar o deputado um personagem que, na opinião dele, está prestando um bom serviço para o país neste momento. ele está destruindo a fraude que o psdb representa. tirou todo esse eleitorado de direita, mais reativo, xenófobo, racista, elitista etc. que existe no país e que votava escondido no armário no psdb. então, o prejuízo que ele está causando ao psdb é mortal, ele é um problema do psdb. para ciro, no entanto, antes de ter pretensão de chegar ao palácio do planalto, bolsonaro deveria tentar ser prefeito do rio como experiência e que a popularidade dele se deve ao fato de ele ter respostas a duas grandes questões dos brasileiros, ainda que toscamente: a corrupção e a violência. se o cara chega ali, na presidência da república, deixando o povo acreditar, falando bandido bom é bandido morto e a ladroeira vai acabar, porque no meu governo não tem, é mentira ou despreparo.']

In [40]:
topic_model.get_representative_docs(24)

['dezessete países registram casos de microcefalia aossociada ao zika. vírus já tem transmissão em 70 países, conforme dados da oms desde 2007; nos estados unidos, autoridades acreditam que surto deve crescer. são paulo - depois de meses de dúvidas sobre a ligação entre vírus e má-formação, e um alerta mundial, 17 países já registram casos de microcefalia associada ao zika, de acordo com o boletim mais recente da organização mundial de saúde (oms). em quatro, não há transmissão local do vírus, mas as mães viajaram a locais onde há epidemia. desde 2007, 70 países tiveram transmissão de zika. o balanço é de 1.926 casos de má-formação no mundo desde 2014. o brasil ainda concentra a maior parte dos registros associados ao zika (1.835). outros 2.957 casos no país seguem em investigação pelo ministério da saúde em 4.223, a relação com vírus e com problemas congênitos foi descartada. na sequência, têm mais notificações de microcefalia colômbia (24) e estados unidos (21). dos registros americanos, três são de mães que contraíram o vírus em outros países. na europa, os três casos de microcefalia na eslovênia e na espanha não são autóctones. com o verão, período mais propício à propagação, os estados unidos já registraram 36 prováveis transmissões locais do vírus na flórida. por isso, o centro de controle e prevenção de doenças (cdc) americano resolveu declarar miami beach polo turístico que movimenta r 24 bilhões anuais um destino não adequado para grávidas. na flórida, o governo tem adotado medidas para combater o aedes aegypti , transmissor da zika. além do fumacê, é estudado o uso de mosquitos transgênicos, que têm filhos estéreis. essa',
 'surto de microcefalia: o governo está sendo omisso. a situação é gravíssima, alerta especialista. o presidente da sociedade brasileira de dengue e arbovirose, artur timerman, acredita que o governo errou ao não agir antes contra o vírus da zika. a doença, transmitida pelo aedes aegypti tem relação com o aumento dos casos de microcefalia no brasil. de acordo com o ministério da saúde já foram 1.761 casos neste ano no ano passado 147 bebês nasceram com o problema. artur afirma que o governo já devia ter desenvolvido um exame capaz de detectar a infecção em larga escala, como existe para a dengue e que, sem isso, não é possível nem saber qual a taxa de grávidas que contraiu zika e desenvolveu a microcefalia. a situação é dramática, afirma ele. pergunta. não há, de fato, dúvidas, de que os casos de microcefalia são causados por zika? resposta. não há a menor dúvida. só não posso dizer ainda qual a real dimensão desse problema, mas o que nós temos visto e discutido com vários colegas de todo o brasil é que a situação é dramática. p. o que leva a tanta certeza, já que não há casos no resto do mundo? r. em 1952 saiu já um trabalho, em fetos de camundongos fêmeas, que mostrava que o zika tinha uma afinidade pelo tecido neurológico desses ratinhos. deixou-se essa informação armazenada e publicada na literatura médica, mas não se deu grande relevância porque não havia casos humanos. esses casos humanos começaram a ser descritos em 2006 e 2007, em epidemias esporádicas nas regiões da floresta de zika, na uganda, onde o vírus havia sido descoberto na década de 1940. em 2009, houve uma epidemia bem maior na polinésia francesa. aqui no brasil, no ano passado a gente já suspeitava que o vírus estava circulando, mas foi somente em abril deste ano que confirmaram 16 casos: oito em natal e oito em recife. em agosto, colegas de pernambuco começaram a notar o crescimento absurdo de casos de microcefalia. eram dois, três casos diários. ao mesmo tempo, um outro médico de salvador começou a ver um número excessivo de casos de uma síndrome neurológica chamada guillain-barré. logo se supõe que pudesse ser o zika porque em um grande percentual dessas crianças que nasceram com microcefalia, as mães apresentaram no início da gravidez uma doença que parece dengue: dores no corpo, dores de cabeça, manchas no corpo e faziam o exame de dengue, dava negativo, faziam o exame de chikungunya, dava negativo, e aí os dois com muita perspicácia pensaram: há mais vírus que o mosquito transmite, que é o zika. já há dois casos de mulheres, de duas grávidas, com fetos com microcefalia cuja pesquisa do líquido amniótico deu positivo para zika. há pesquisas já de positivo para vírus em pessoas com guillain-barré, e acho muito importante de salientar é que na polinésia, nessa epidemia de 2009, teve um aumento nos casos de microcefalia, mas eles não tinham relatado porque não tinham feito a associação. p. e o que fazer agora? r. a gente precisa saber a real extensão dos casos. é muito mais do que os que estão aparecendo até agora. há grávidas que foram infectadas há seis meses. o que vai acontecer? quando o vírus começar a circular, se já não está, no sudeste e centro-oeste do brasil, só vamos começar a ver a repercussão em seis meses, oito meses, nove meses, ou seja, do meio para o fim do ano que vem. a urgência que a gente tem agora não é discutir a causalidade, que já está estabelecida. nós precisamos saber a real dimensão. quantas grávidas estão se infectando pelo vírus? quais as chances de uma grávida se infectar e transmitir isso para seu feto? a gente só vai saber isso quando dispuser de um teste sorológico. a urgência número zero e estamos atrasados porque se tem certeza de que o vírus está circulando aqui desde abril é elaborar um teste de diagnóstico que possa ser usado em larga escala para sabermos quantos brasileiros estão infectados pelo zika e qual o percentual de casos de transmissão para o feto. são questionamentos que a gente ainda não consegue responder. p. qual a diferença entre o exame de sorologia e o da p roteína c reativa (pcr), que já é feito? r. quando se quer detectar uma infecção causada por um vírus, há dois métodos que se pode usar. um é a amplificação do material genético do vírus, que é o pcr. ele detecta o próprio vírus, mas é trabalhoso, custoso, demanda um laboratório de excelência. não é um método usado para testar grandes populações. todos esses casos em que já se diagnosticou o zika foram determinados pelo pcr. já a sorologia é um método que é mais usado em saúde pública porque detecta a formação de anticorpos na pessoa infectada. quando o vírus contagia alguém, essa pessoa forma anticorpos que evidenciam que houve a infecção pelo vírus e podem ser vistos em um exame de sangue. p. e por que isso não foi desenvolvido ainda? r. não é difícil desenvolver um teste sorológico. precisa de dinheiro. precisa financiar laboratórios de pesquisa para que eles se capacitarem para fazer esse teste, que é fundamental para dimensionarmos a real grandeza do que está acontecendo. p. há uma polêmica em relação ao conselho de se engravidar. a mulher, que puder, deve evitar? r. com toda essa insegurança, essa zona nebulosa que estamos vivendo... eu entendo a gravidade do que vou falar, mas temos que falar para as mulheres evitarem a gravidez agora até que a gente tenha a real dimensão do problema. espero que nós nos capacitemos o mais rapidamente possível para poder dimensionar isso e fazer a orientação mais adequada para que as pessoas exerçam sua escolha informadas. p. isso vale para todas as regiões ou só para o nordeste, neste momento? r. o maior número de casos de dengue neste ano foi em são paulo. se tem muitos casos de dengue, tem muitos mosquitos vetores, que transmitem também o chikungunya e o zika. por que não teria casos dessas doenças aqui? vírus e mosquito vão circular onde se fornece condições para tal. mas não sabemos a real dimensão disso porque não temos recursos para saber como a sorologia. a sorologia para a dengue já é rotina, qualquer laboratório faz. quantos desses casos de dengue já não eram zika ou chikungunya? p. então ainda não sabemos se o zika chegou ou não no sudeste? r. sem dúvida. quem tem certeza? eu não tenho! p. mas se sudeste tivesse muitos casos não seria natural ter muito mais microcefalia? r. aqui em são paulo já temos quatro casos. mas o que acontece na história das epidemias, e com a dengue é muito clássico, é que o vírus é introduzido pela região norte e nordeste do brasil. p. por quê? r. o vírus da dengue foi introduzido no brasil por meio da américa central. e as populações do norte e do nordeste do brasil tem contato muito mais frequente com aquelas populações do que o sudeste. a história das epidemias mostra isso. quando há pessoas infectadas pelo vírus, o aedes vai se infectando. essa interação inicial entre o mosquito e pessoas, normalmente não é muito eficaz em termos de transmissão. na história das epidemias, você vê que depois de um ou dois anos do início da circulação do vírus é que aumenta a taxa da transmissão. por isso as epidemias começam com surtos isolados em alguns locais, começam a aumentar gradativamente o número de pessoas infectadas e você tem uma explosão de casos normalmente três, quatro anos depois de um determinado vírus ser introduzido em uma determinada comunidade. então, provavelmente, o vírus zika já está circulando no nordeste há três, quatro anos. e só agora que foi identificado. aqui no sudeste, provavelmente, ele já vem sendo introduzido há algum tempo, talvez não com a importância de casos que tenha no nordeste. a explosão de casos de microcefalia agora é lá. provavelmente isso vai se dar depois no sudeste. a não ser que nós consigamos eliminar o mosquito, o que é impossível de acontecer, essa transmissão vai acontecer. p. então teremos anos bastante difíceis? r. pois é. agora você entende porque eu trato a situação como dramática. sem dúvida, é uma situação dramática, inédita. todos os dias se acumulam novos e novos casos, mas não estamos conseguindo ligar os pontos. quem vai coordenar e acelerar a nossa capacitação em fazer o diagnóstico? qual o percentual de grávidas que têm zika agora? quantas devem se infectar nos próximos seis meses? qual a chance de uma grávida se infectar e passar isso para a criança? temos que esclarecer o que está acontecendo. p. mas isso não demora para ser levantado? r. isso já deveria estar pronto. o teste sorológico não é difícil de ser elaborado. o país tem capacidade para isso, pode contar com recursos de fora do brasil, com a organização mundial da saúde e o cdc centro de controle e prevenção de doenças, em português norte-americano, que certamente nos ajudariam a acelerar isso. tem que ser feito para ontem. p. na bahia, desde o meio do ano já se sabia do aumentos da síndrome de guillain-barré. já se sabia que ela era uma possível consequência do zika. o governo já não deveria ter tomado providências contra o zika neste momento? r. não tenho dúvidas quanto a isso. os relatos de uganda, muito ruins, e mesmo os da polinésia, que são melhorzinhos, mostravam que apenas cerca de 20 das pessoas infectadas pelo vírus zika têm manifestação clínica. os mais de 60.000 casos suspeitos de zika na bahia provavelmente seriam, na verdade, apenas 20 do total de casos de infectados pelo zika. é mais de um milhão de casos. a hora de valorizar isso era oito meses atrás. nós perdemos muito tempo. essa resposta ao zika é o comprovante maior de desestruturação de nosso serviço de atenção à saúde no brasil. p. isso também se mostra na dificuldade de combater o aedes aegypti ou é realmente difícil conseguir controlar ou zerar a quantidade de mosquitos? r. tomara que as próximas gerações consigam viver em uma cidade estruturada para receber pessoas e não mosquitos. nós fizemos uma urbanização caótica, juntamos um monte de gente, sem fornecimento de água adequado, sem coleta de esgoto e de lixo. são cidades totalmente impermeabilizadas. para as próximas gerações viverem em uma sociedade que seja mais salubre para as pessoas precisamos mudar o modelo de urbanização. ter mais áreas verdes, controle de construções, ver qual o tipo de asfalto usado, se é poroso, permeável. sei que não é para amanhã. mas se quisermos mudar algo a médio e longo prazo é isso que temos que fazer: mudar o modelo de urbanização. hoje o governo faz essas campanhas para que as pessoas cuidem das plantas de casa, não deixem água parada. isso é importante, claro, mas é apagar o incêndio com copo de água. vamos diminuir um pouco o risco, a quantidade de mosquitos, mas será ínfimo. o que é urgente agora e que, talvez, seja mais factível do que a minha utopia de urbanização, é isolar rápido esse vírus, ver suas caracterizações e tentar fazer uma vacina o mais rapidamente possível. p. mas ainda não conseguimos nem implementar a vacina de dengue, que já circula há tanto tempo... r. a gente vai ter que torcer para o vírus do zika ser só um vírus e não ser como a dengue, que são quatro. e para o zika não ter mutação. porque isso vai facilitar se fazer a vacina. a dengue são quatro sorotipos. a vacina é muito boa para um sorotipo, mas não serve muito para outro. ninguém sabe se o zika tem só um sorotipo e que não sofre mutação. temos que torcer para isso. p. não há coisas urgentes que o governo pode fazer contra o mosquito, como fumigar as casas e as ruas, por exemplo? r. fumigar é praticamente usar ddt e os mosquitos já são quase todos resistentes ao ddt. p. então a solução mais próxima agora é mesmo a vacina? r. a médio prazo, sim. agora, a curto prazo é orientar as pessoas sobre os hábitos do mosquito. é um mosquito que voa de manhã, entre 9h e 13h , voa baixo, a no máximo 1, 5 metro. é preciso usar calça e blusa de manga longa, meia. colocar repelentes para os quais ele não é resistente, como os de icaridina. ddt e citronela não têm efeito.',

In [43]:
outliers = [
    documentos[i]
    for i, topic in enumerate(topics)
    if topic == -1
]

print(f'Total de outliers: {len(outliers)}')

Total de outliers: 2647

In [44]:
for i, texto in enumerate(outliers[:10]):
    print(f'\n--- OUTLIER {i+1} ---')
    print(texto[:1000])

--- OUTLIER 1 ---
tico santa cruz, o papagaio de pirata do pt, tenta defender dilma e leva porretada de internauta. tico santa cruz, acostumado a discursar para um bando de petistas alienados, encontrou pela frente uma parada dura!. o flagra foi publicado pelo site bolsonaro opressor o músico publicou (nas redes sociais) uma imagem com algumas manchetes dos principais jornais do país em que a pauta era pedalar não é crime . tico tentou induzir seus seguidores a imaginar que dilma não havia cometido crime algum. durante a última semana, o mpf concluiu que as denominadas pedaladas fiscais não configuram crimes comuns. vamos repetir: as pedaladas ficais (de acordo como mpf) não configuram crimes comuns ! vamos repetir novamente: crimes comuns! o detalhe é que o notável músico não se deu ao trabalho ler as notícias (na íntegra) citadas em sua postagens. um seguidor da página argumentou: o artista respondeu imediatamente: eis que veio a paulada do internauta:

--- OUTLIER 2 ---
alemanha volta a fazer alerta e pede para população estocar água, comida e remédios. um relatório da emissora alemã dw deutsche welle diz que este tipo de movimento não acontece desde o fim da guerra fria (19451989). o anúncio foi feito há alguns meses e está sendo reforçado novamente. angela merkel, chanceler do governo alemão, emitiu um documento oficial orientando seus cidadãos a estocarem alimentos, água e outros suprimentos para um provável caso de catástrofe ou ataque nuclear . a diretriz está contida em um documento-estratégia da defesa civil do governo. o texto diz que cidadãos residentes no país devem providenciar um estoque de dez dias de comida, água, dinheiro e medicamentos para que fiquem alojados enquanto o governo possa controlar situações de emergência.

--- OUTLIER 3 ---
mpf vai investigar autenticidade dos recibos apresentados pela alma mais honesta deste país. . o ministério público federal acabou de apresentar (à justiça federal) um incidente de falsidade (previsto em capítulo do código de processo penal, em seus artigos 145 a 148) referente aos recibos apresentados pela defesa do ex-presidente. resumindo: os recibos de aluguéis apresentados por lula (para comprovar o pagamento de supostos aluguéis do apartamento vizinho ao que ele mora ) no último dia 25 passarão por perícia técnica e serão investigados. o contrato teria sido firmado entre glaucos da costa marques (suposto dono do apto e laranja de lula, segundo o mpf) e a mulher do petista, dona marisa letícia. anota aí, caro internauta ... é mais um crime na capivara (ficha criminal) do ex-presidente!

--- OUTLIER 4 ---
ex-presidente diz que é mais honesto do que todos os funcionários do mp e da polícia federal juntos. vejam a última do petista. após sérgio moro aceitar o pedido do mpf e o ex-presidente ter se tornado réu em um processo, ele soltou outra pérola: honestidade não é mérito, é obrigação. fazer as coisas direito é obrigação nossa. duvido que um cidadão do mp seja mais honesto do que eu, ou que na pf tem alguém mais honesto que eu. pode ter igual, mas mais honesto não , disse lula. e o pior de tudo é que ele mente e a cara não fica vermelha! são muitos anos de treinamento!

--- OUTLIER 5 ---
cara de pau não tem limites: zé celso aciona mp contra silvio santos. o teatro oficina procurou o ministério público federal (mpf) nesta terça-feira na tentativa de violar os direitos de silvio santos, que deseja erguer três torres residenciais de cem metros de altura cada uma. as informações são da veja. o empresário é dono dos terrenos em volta do teatro e executa seu direito de propriedade, negando-se a trocá-los por outros, oferta feita a ele pelo ministério do planejamento. o grupo teatral, que fez sua sede no local há cerca de sessenta anos e ocupa um prédio que leva a assinatura de lina bo bardi (a mesma do masp e do sesc pompeia), alega danos ao projeto da arquiteta, que prevê a contracenação com o bairro do bexiga e a cidade através do janelão aberto em uma das paredes do edifício

--- OUTLIER 6 ---
delação de marcos valério promete revelar 20 políticos figurões envolvidos em corrupção. a delação premiada de marcos valério (acordo feito com o ministério público de mg) promete revelar de 15 a 20 autoridades, segundo o advogado responsável pelas negociações. marcos valério foi condenado a 37 anos de prisão pelo esquema do chamado mensalão do pt e está preso desde 2012 entre as autoridades estariam integrantes atuais do presidente interino michel temer, além de mais políticos do pt, psdb, pmdb e outras siglas. todas as pessoas citadas na delação de valério teriam ligação com crimes do mensalão mineiro , do mensalão do pt e também da operação lava-jato . o advogado de marcos valério revelou em entrevista ao jornal valor: tem gente sobre quem ele pode falar e ainda não apareceu. tem deputados estaduais, federais, senadores e ex-senadores. alguns não teriam sido reeleitos se ele já tivesse feito a delação , revelou o advogado jean robert kobayashi . tem também gente do atual governo de

--- OUTLIER 7 ---
pf investiga ex-ministro petista suspeito de desviar r 102 milhões e encontra emails enviados para toffoli. a justiça de são paulo enviou para o stf um arquivo contendo mensagens e emails do celular de carlos gabas enviadas para o ministro dias toffoli. gabas, que é ex-ministro dos governos lula e dilma, é investigado juntamente com o ex-ministro paulo bernardo por desvio de r 102 milhões da previdência. a justiça federal negou um pedido do mpf de sp para ter acesso às comunicações (e-mails e mensagens de celular). a informação é do estadão. essas mensagens foram encontradas durante o cumprimento de um mandado de busca e apreensão realizada pela operação custo brasil.

--- OUTLIER 8 ---
o sujo falando do mal lavado? igreja católica anuncia que fará discurso sobre fake news. o papa francisco anunciou que fará um discurso sobre fake news em janeiro de 2018. para comemorar o dia mundial das comunicações sociais, a igreja católica (nada contra a religião) irá meter o bedelho onde não foi chamada. vamos ser sinceros! igreja falando de fake news ... eles fazem isso há mais de 2000 anos, porém de uma maneira um pouco diferente. uma das religiões mais poderosas e capitalistas do mundo, a igreja católica possui um patrimônio estimado em cerca de 3 trilhões de dólares em bens imóveis. pergunta : adivinha como eles fizeram essa fortuna? r : espalhando fake news nas missas. o vaticano informou que o tema da mensagem (que será divulgada em janeiro2018) será a verdade vos tornará livres notícias falsas e jornalismo para a paz. abaixo o tweet do papa: ps: não me venham com mi mi mi falando que estamos desrespeitando deus! deus é uma coisa ... religião é outra totalmente diferente! a

--- OUTLIER 9 ---
mainardi publica vídeo e acaba com jornalista: bandido, vou te processar e fechar essa joça. diogo mainardi teve seu nome citado pelo delator henrique valladares. o executivo disse que diogo foi visto jantando no restaurante gero, rj, junto aécio neves e o empresário alexandre accioly. mainardi se defendeu e publicou uma postagem em seu site dizendo que valladares é mentiroso. ele soltou os cachorros no jornalista renato rovai. leia mais...

--- OUTLIER 10 ---
publicitário faz versão de faroeste caboclo com eike batista. o resultado? 12 milhões de visualizações. pedro guadalupe tem 31 anos e trabalha com informática desde os 12. reunindo técnica, humor e conhecimento, pedro se tornou um expert em publicidade. a última tacada do profissional é uma paródia da música faroeste caboclo na versão eike batista. somente na rede social facebook, o vídeo já teve mais de 12 milhões de visualizações. a música é uma parceria de joão basílio e guadalupe. vale a pena conferir:

In [45]:
topic_info = topic_model.get_topic_info()

topicos = topic_info[
    topic_info['Topic'] != -1
][['Topic', 'Count', 'Name']]

print(topicos.to_string(index=False))

 Topic  Count                                            Name
     0    363                   0_brasil_país_presidente_lula
     1    346                 1_norte_coreia_coreia norte_kim
     2    266                   2_bilhões_governo_ano_milhões
     3    261            3_odebrecht_milhões_dinheiro_delação
     4    203         4_dilma_impeachment_presidente_rousseff
     5    188                   5_stf_supremo_ministro_mendes
     6    181                    6_lula_ex presidente_moro_ex
     7    146                7_candidato_alckmin_partido_psdb
     8    138                       8_igreja_pastor_deus_papa
     9    137                           9_anos_mãe_jovem_bebê
    10    107               10_avião_aeronave_acidente_piloto
    11    104                           11_prisão_preso_pf_ex
    12     94           12_manifestantes_ato_protesto_polícia
    13     79                        13_lula_dilma_petista_pt
    14     78                       14_anos_morreu_ator_corpo
    15     72                   15_cantor_música_marrone_ator
    16     70               16_senador_lindbergh_senado_renan
    17     62             17_rio_segurança_intervenção_forças
    18     59      18_presos_detentos_presídios_penitenciária
    19     54         19_temer_presidente_michel_michel temer
    20     49                    20_síria_ataque_assad_rússia
    21     48           21_polícia federal_pf_federal_polícia
    22     48                     22_lava jato_lava_jato_lula
    23     48                    23_água_furacão_irma_mariana
    24     47                       24_vírus_zika_casos_febre
    25     46   25_maia_rodrigo maia_câmara_presidente câmara
    26     45                26_tse_chapa_cassação_julgamento
    27     45            27_festival_carnaval_teatro_salvador
    28     40           28_sírio libanês_sírio_libanês_médico
    29     39                      29_arte_nu_exposição_museu
    30     38                30_terra_planeta_nasa_cientistas
    31     37               31_senado_senadores_proposta_foro
    32     37             32_denúncia_câmara_deputados_contra
    33     36              33_olímpica_vila_vila olímpica_rio
    34     36             34_lula_ex presidente_presidente_ex
    35     34                  35_carne_fraca_carne fraca_brf
    36     34                 36_vereador_paulista_beto_vídeo
    37     33            37_futebol_corinthians_francês_clube
    38     32                      38_ator_zezé_mayer_assédio
    39     32        39_livro_literatura_shakespeare_escritor
    40     31                40_apartamento_lula_imóvel_sítio
    41     29              41_demissão_temer_ministro_palácio
    42     29            42_câncer_células_pacientes_pesquisa
    43     29               43_globo_vivo_emissora_rede globo
    44     28           44_mortes_mortos_homicídios_violência
    45     27             45_facebook_rede social_rede_social
    46     26                   46_vida_câncer_pessoas_muitas
    47     26                      47_lula_moro_depoimento_ex
    48     25 48_trump_donald_donald trump_presidente estados
    49     25             49_carro_acidente_motorista_veículo
    50     25                    50_fidel_cuba_castro_cubanos
    51     24                          51_lula_moro_defesa_ex
    52     24          52_violência_homicídios_brasil_pessoas
    53     24                    53_rússia_putin_russos_russo
    54     24                 54_ano_2017_fatos_retrospectiva
    55     23       55_renan_senado_calheiros_renan calheiros
    56     23                 56_triplex_guarujá_lula_solaris
    57     22            57_tiririca_deputado_câmara_discurso
    58     21      58_educação_ensino_universidade_estudantes
    59     20            59_reforma_temer_previdência_governo
    60     20         60_dilma_rousseff_dilma rousseff_brasil
    61     19             61_palocci_odebrecht_ex_ex ministro
    62     18      62_jornalista_jornalistas_reinaldo_boechat
    63     18               63_nacionalismo_bauman_mundo_ódio
    64     17        64_passaporte_lula_federal_passaporte ex
    65     17              65_aécio_neves_aécio neves_senador
    66     17                  66_cão_cachorro_animais_animal
    67     17              67_pessoas_atentado_ataque_londres
    68     16           68_hospital_internado_passa bem_passa
    69     16           69_internet_banda larga_larga_hackers
    70     15    70_aplicativos_uber_caminhoneiros_transporte
    71     15             71_pf_diretor geral_daiello_diretor
    72     15           72_prefeito_doria_vereadores_crivella
    73     15     73_aposentadoria_idade_reforma_idade mínima

In [46]:
df['topico_bertopic'] = topics

In [47]:
df[['id', 'arquivo', 'topico_bertopic', 'texto_original']].head()

,id,arquivo,topico_bertopic,texto_original
0,1,1170.txt,28,Falso médico é preso pela PM de Santa Catarina...
1,2,1688.txt,0,Antes da confirmação da morte de Teori Zavasck...
2,3,1863.txt,55,Senador que assume o lugar de Renan foi flagra...
3,4,1563.txt,3,"Repórter relata conversa entre deputados: ""A D..."
4,5,3556.txt,12,Governo repressor e comunista usa exército par...

In [48]:
topic_info = topic_model.get_topic_info()

topic_info = topic_info[
    topic_info['Topic'] != -1
][['Topic', 'Count', 'Name']]

topic_info

    Topic  Count                                          Name
1       0    363                 0_brasil_país_presidente_lula
2       1    346               1_norte_coreia_coreia norte_kim
3       2    266                 2_bilhões_governo_ano_milhões
4       3    261          3_odebrecht_milhões_dinheiro_delação
5       4    203       4_dilma_impeachment_presidente_rousseff
..    ...    ...                                           ...
70     69     16         69_internet_banda larga_larga_hackers
71     70     15  70_aplicativos_uber_caminhoneiros_transporte
72     71     15           71_pf_diretor geral_daiello_diretor
73     72     15         72_prefeito_doria_vereadores_crivella
74     73     15   73_aposentadoria_idade_reforma_idade mínima

[74 rows x 3 columns]

In [49]:
topic_info['tema'] = ''

In [81]:
mapa_temas = {
    0: 'Política',
    1: 'Internacional',
    2: 'Economia',
    3: 'Corrupção',
    4: 'Política',
    5: 'Política',
    6: 'Política',
    7: 'Política',
    8: 'Religião',
    9: 'Sociedade',
    10: 'Acidentes',
    11: 'Segurança',
    12: 'Política',
    13: 'Política',
    14: 'Entretenimento',
    15: 'Entretenimento',
    16: 'Política',
    17: 'Segurança',
    18: 'Segurança',
    19: 'Política',
    20: 'Internacional',
    21: 'Segurança',
    22: 'Corrupção',
    23: 'Meio Ambiente',
    24: 'Saúde',
    25: 'Política',
    26: 'Política',
    27: 'Cultura',
    28: 'Saúde',
    29: 'Cultura',
    30: 'Ciência',
    31: 'Política',
    32: 'Política',
    33: 'Esportes',
    34: 'Política',
    35: 'Alimentação',
    36: 'Política',
    37: 'Esportes',
    38: 'Entretenimento',
    39: 'Cultura',
    40: 'Política',
    41: 'Política',
    42: 'Saúde',
    43: 'Mídia',
    44: 'Segurança',
    45: 'Tecnologia',
    46: 'Saúde',
    47: 'Política',
    48: 'Internacional',
    49: 'Acidentes',
    50: 'Internacional',
    51: 'Política',
    52: 'Segurança',
    53: 'Internacional',
    54: 'Sociedade',
    55: 'Política',
    56: 'Política',
    57: 'Política',
    58: 'Educação',
    59: 'Economia',
    60: 'Política',
    61: 'Corrupção',
    62: 'Mídia',
    63: 'Política',
    64: 'Política',
    65: 'Política',
    66: 'Animais',
    67: 'Internacional',
    68: 'Saúde',
    69: 'Tecnologia',
    70: 'Transportes',
    71: 'Política',
    72: 'Política',
    73: 'Economia'
}

In [82]:
topic_info['tema'] = topic_info['Topic'].map(mapa_temas)

In [83]:
topic_info[['Topic', 'Count', 'Name', 'tema']]

    Topic  Count                                          Name           tema
1       0    363                 0_brasil_país_presidente_lula       Política
2       1    346               1_norte_coreia_coreia norte_kim  Internacional
3       2    266                 2_bilhões_governo_ano_milhões       Economia
4       3    261          3_odebrecht_milhões_dinheiro_delação      Corrupção
5       4    203       4_dilma_impeachment_presidente_rousseff       Política
..    ...    ...                                           ...            ...
70     69     16         69_internet_banda larga_larga_hackers     Tecnologia
71     70     15  70_aplicativos_uber_caminhoneiros_transporte    Transportes
72     71     15           71_pf_diretor geral_daiello_diretor       Política
73     72     15         72_prefeito_doria_vereadores_crivella       Política
74     73     15   73_aposentadoria_idade_reforma_idade mínima       Economia

[74 rows x 4 columns]

In [84]:
for topic in [0, 2, 3, 9, 14, 23, 28, 35, 36, 43, 46, 54, 63, 68, 70, 73]:
    print(f'\n========== TÓPICO {topic} ==========')
    print(topic_model.get_topic(topic)[:10])

========== TÓPICO 0 ==========
[('brasil', np.float64(0.013682024197759761)), ('país', np.float64(0.007358838691703302)), ('presidente', np.float64(0.006870159021953427)), ('lula', np.float64(0.0056173653802873745)), ('brasileiros', np.float64(0.005185127281866319)), ('brasileiro', np.float64(0.004910664251309181)), ('temer', np.float64(0.004898818470295437)), ('política', np.float64(0.00470586834950469)), ('governo', np.float64(0.00449558909555325)), ('brasileira', np.float64(0.004402832896259538))]

========== TÓPICO 2 ==========
[('bilhões', np.float64(0.012547523737331073)), ('governo', np.float64(0.009005187282879464)), ('ano', np.float64(0.008536010733366788)), ('milhões', np.float64(0.005864468657362612)), ('2017', np.float64(0.005831774431370531)), ('trabalho', np.float64(0.005687387535212013)), ('feira', np.float64(0.005480898533781865)), ('mil', np.float64(0.005474943437246456)), ('mercado', np.float64(0.005249460718951768)), ('empresas', np.float64(0.005246147807387492))]

========== TÓPICO 3 ==========
[('odebrecht', np.float64(0.01680516636087433)), ('milhões', np.float64(0.016715934066494312)), ('dinheiro', np.float64(0.010922665648022918)), ('delação', np.float64(0.009779440024144147)), ('ex', np.float64(0.00970660478915502)), ('propina', np.float64(0.008795926191729083)), ('campanha', np.float64(0.008190561788095331)), ('lula', np.float64(0.008020841001434601)), ('mil', np.float64(0.007782300346374199)), ('dilma', np.float64(0.006973413874610688))]

========== TÓPICO 9 ==========
[('anos', np.float64(0.01613744166528117)), ('mãe', np.float64(0.015035524217083809)), ('jovem', np.float64(0.00852627153732191)), ('bebê', np.float64(0.008246201157822852)), ('filha', np.float64(0.00818021493318721)), ('casa', np.float64(0.008067101012244797)), ('mulher', np.float64(0.007816375207698343)), ('criança', np.float64(0.007441245315359053)), ('polícia', np.float64(0.007199902126792953)), ('crime', np.float64(0.007071583449079124))]

========== TÓPICO 14 ==========
[('anos', np.float64(0.019227043647041163)), ('morreu', np.float64(0.018041959410082267)), ('ator', np.float64(0.014747346994882938)), ('corpo', np.float64(0.012711921395897852)), ('jornalista', np.float64(0.010838924517525437)), ('montagner', np.float64(0.009657375658983237)), ('marisa', np.float64(0.009227760591867399)), ('câncer', np.float64(0.00911287552356672)), ('morte', np.float64(0.008840671769727632)), ('morre', np.float64(0.008735876891361669))]

========== TÓPICO 23 ==========
[('água', np.float64(0.03711521058828843)), ('furacão', np.float64(0.018039597165112553)), ('irma', np.float64(0.010889688988213025)), ('mariana', np.float64(0.01087370498069666)), ('rio', np.float64(0.010860664689655596)), ('doce', np.float64(0.010659070377492875)), ('ambiental', np.float64(0.010525870961077466)), ('samarco', np.float64(0.010341716083380428)), ('rio doce', np.float64(0.009392400628962716)), ('mundial água', np.float64(0.009146361820185378))]

========== TÓPICO 28 ==========
[('sírio libanês', np.float64(0.03200494368947833)), ('sírio', np.float64(0.03194504674948256)), ('libanês', np.float64(0.03190664212953274)), ('médico', np.float64(0.03129064635899314)), ('hospital', np.float64(0.030263330520612756)), ('marisa', np.float64(0.02940322663543951)), ('hospital sírio', np.float64(0.021269547459354613)), ('ex primeira', np.float64(0.01992165313863864)), ('primeira dama', np.float64(0.019806996253804665)), ('dama', np.float64(0.019670975103627527))]

========== TÓPICO 35 ==========
[('carne', np.float64(0.05660593364861484)), ('fraca', np.float64(0.025567339880191973)), ('carne fraca', np.float64(0.025537752017056922)), ('brf', np.float64(0.024356840007117665)), ('carnes', np.float64(0.02002213225874077)), ('operação carne', np.float64(0.016986135341145108)), ('produtos', np.float64(0.016588492044517986)), ('operação', np.float64(0.016009710803854695)), ('alimentos', np.float64(0.015476807135578152)), ('trapaça', np.float64(0.012166563611839295))]

========== TÓPICO 36 ==========
[('vereador', np.float64(0.012806675264062282)), ('paulista', np.float64(0.012654743033867275)), ('beto', np.float64(0.012034801272165207)), ('vídeo', np.float64(0.010240485759892731)), ('policial', np.float64(0.009334334514449746)), ('beto barbosa', np.float64(0.009160052456893992)), ('cidade', np.float64(0.00874013102334957)), ('estudantes', np.float64(0.008546246060513499)), ('pm', np.float64(0.00850786694252604)), ('prefeita', np.float64(0.008364137899009519))]

========== TÓPICO 43 ==========
[('globo', np.float64(0.04614235406221362)), ('vivo', np.float64(0.02199647891595824)), ('emissora', np.float64(0.017496531263268188)), ('rede globo', np.float64(0.015850595973602954)), ('tv', np.float64(0.01578224376634842)), ('jornal', np.float64(0.015449358275849624)), ('globo news', np.float64(0.014587452727616837)), ('news', np.float64(0.013486558718369516)), ('rede', np.float64(0.012671542474294452)), ('jornalismo', np.float64(0.012633657222934327))]

========== TÓPICO 46 ==========
[('vida', np.float64(0.013840573060593228)), ('câncer', np.float64(0.012886473854108994)), ('pessoas', np.float64(0.011623220298322958)), ('muitas', np.float64(0.010571875369895659)), ('dormir', np.float64(0.010495434455498994)), ('sono', np.float64(0.010212182661970328)), ('doença', np.float64(0.009781333284280118)), ('criança', np.float64(0.009052273474844733)), ('day', np.float64(0.008469415964696228)), ('horas', np.float64(0.00830536568804749))]

========== TÓPICO 54 ==========
[('ano', np.float64(0.038089400099810204)), ('2017', np.float64(0.03529085921283023)), ('fatos', np.float64(0.027131997847295995)), ('retrospectiva', np.float64(0.024036700222491096)), ('retrospectiva 2017', np.float64(0.023426837685851326)), ('marcaram', np.float64(0.020795013362128655)), ('marcantes', np.float64(0.01937941258802636)), ('g1', np.float64(0.019162438688824685)), ('região', np.float64(0.01896535945753396)), ('2017 principais', np.float64(0.017114285815285495))]

========== TÓPICO 63 ==========
[('nacionalismo', np.float64(0.01222824924725954)), ('bauman', np.float64(0.01222824924725954)), ('mundo', np.float64(0.010355755895431501)), ('ódio', np.float64(0.009928484809668217)), ('esquerda', np.float64(0.009080943365402378)), ('anos', np.float64(0.008485943437234942)), ('marilena', np.float64(0.008222252194982661)), ('esquerdismo', np.float64(0.008042459732353464)), ('sociedade', np.float64(0.007889097761697416)), ('política', np.float64(0.007745554709145654))]

========== TÓPICO 68 ==========
[('hospital', np.float64(0.02805462106658359)), ('internado', np.float64(0.023849313655926966)), ('passa bem', np.float64(0.022894698188824284)), ('passa', np.float64(0.02004197957195861)), ('cirurgia', np.float64(0.01816823609256953)), ('barrichello', np.float64(0.017906404814942503)), ('alta', np.float64(0.016677304298179065)), ('marca passo', np.float64(0.01648026744814832)), ('bem', np.float64(0.015313383457784255)), ('dores', np.float64(0.015096379322405566))]

========== TÓPICO 70 ==========
[('aplicativos', np.float64(0.039284043107642774)), ('uber', np.float64(0.03290602727442105)), ('caminhoneiros', np.float64(0.027236386395605595)), ('transporte', np.float64(0.025439086640318787)), ('motoristas', np.float64(0.02425962203276183)), ('texto', np.float64(0.018170655301826835)), ('taxistas', np.float64(0.01761682140929905)), ('emendas', np.float64(0.016500907950429057)), ('estradas', np.float64(0.016342022639884792)), ('multa', np.float64(0.015614396574512975))]

========== TÓPICO 73 ==========
[('aposentadoria', np.float64(0.023061567345872207)), ('idade', np.float64(0.020797406893762027)), ('reforma', np.float64(0.01858395729831609)), ('idade mínima', np.float64(0.01725782438485859)), ('previdência', np.float64(0.017210507185103953)), ('mínima', np.float64(0.015889554389662948)), ('principais', np.float64(0.012583548342597608)), ('governo', np.float64(0.012583160046527646)), ('saque', np.float64(0.012498509666661143)), ('pispasep', np.float64(0.012305460990955745))]

In [85]:
for topic in [0, 2, 3, 9, 14, 23, 28, 35, 36, 43, 46, 54, 63, 68, 70, 73]:
    print(f'\n========== TÓPICO {topic} ==========')
    docs = topic_model.get_representative_docs(topic)

    for i, doc in enumerate(docs[:2]):
        print(f'\nDocumento {i+1}:')
        print(doc[:500])

========== TÓPICO 0 ==========

Documento 1:
a defesa de aécio neves exigiu que o stf afaste edson fachin da relatoria do processo que o afasta do senado. nunca o samba do crioulo doido foi tão atual como no brasil hoje, como lembra eliane cantanhêde na coluna no estadão. nesta nau dos insensatos, a defesa escolhe o juiz de acordo com as conveniências do réu e o fato de ele já ter delinquido em outra ocasião o autoriza a fazê-lo. quanto mais diversas forem as causas contra o acusado mais ele se acha no direito de se livrar de quem o conden

Documento 2:
temer pode entregar o poder aos militares após renuncia. temer está em constante contato com os comandantes das forças armadas nos últimos dias. durante as manifestações em brasília os atos de vandalismos mostraram ao brasil o que podem vir a ser os dias após o impeachment. acossado por denúncias de delatores da jf na lava jato, o presidente michel temer manteve uma reunião com o ministro da defesa, raul jungmann, e os três comandantes das forças armadas: aeronáutica, marinha e exército. muitos

========== TÓPICO 2 ==========

Documento 1:
saiba como foi a semana na economia. redução da taxa básica de juros, resultado do pib e acordo de leniência firmado pela jbs foram destaques. conforme esperado pelos economistas, o banco central reduziu a selic, a taxa básica de juros, em 1 ponto porcentual. outro resultado esperado era do produto interno bruto (pib) do brasil, que registrou alta após oito trimestres no vermelho. confira a seguir um resumo dos acontecimentos mais relevantes dos últimos dias. pib sobe 1 no 1º trimestre o produto

Documento 2:
nova pauta do governo no congresso inclui propostas que sequer foram apresentadas; outras estão há anos em tramitação. governo anunciou pacote de 15 medidas prioritárias após desistir de reforma da previdência. entre elas está o projeto que dá autonomia ao banco central, que é de 1989.. o governo divulgou nesta semana que, após desistir de aprovar no congresso a reforma da previdência, vai se dedicar a aprovar um pacote de 15 medidas consideradas prioritárias para a área econômica. o g1 fez um l

========== TÓPICO 3 ==========

Documento 1:
delação de ex-diretor da odebrecht atinge temer e cúpula do pmdb. cláudio melo filho disse que o presidente pediu, em 2014, r 10 milhões ao empreiteiro marcelo odebrecht. presidência disse repudiar delação.. no acordo de delação premiada, o ex-diretor de relações institucionais da odebrechet cláudio melo filho dedica um capítulo ao relacionamento que tinha com o presidente michel temer. os relatos fazem parte de um depoimento de 82 páginas que ele deu ao ministério público, no qual fala sobre do

Documento 2:
veja quem são os políticos que embolsaram propina da odebrecht (e quanto eles ganharam). a delação da odebrecht, também conhecida como delação do fim do mundo, pode colocar na cadeia os políticos mais influentes do governo temer. veja quem são e quanto cada um embolsou em propina. a odebrecht gastou pelo menos r 88 milhões em propina, caixa dois e doações legais para campanhas de 48 políticos entre 2006 e 2014. é o que mostra um levantamento feito pela folha, com base na delação premiada do ex-e

========== TÓPICO 9 ==========

Documento 1:
jovem é agredido em baile funk na virada do ano em itupeva; ele está internado no hospital são vicente de paulo e seu estado de saúde é considerado estável. caso é investigado como tentativa de homicídio. um rapaz de 22 anos foi espancado por outros jovens, na madrugada de segunda-feira (1º), durante um baile funk na virada do ano, no parque das hortênsias, em itupeva (sp). família recebeu imagens do rapaz sendo agredido (veja acima). um suspeito foi preso. segundo informações de um familiar, qu

Documento 2:
suspeita de matar filha em itapetininga perdeu guarda da menina em 2012 por abandoná-la após o parto. mãe chegou a ser entrevistada em 2016, em reportagem da tv tem sobre pais que recuperam a guarda dos filhos. ela e o marido estão presos em itapetininga (sp).. a jovem de 24 anos que foi presa com o marido no sábado (3), suspeita de espancar e matar a filha de cinco anos, em itapetininga (sp) , tinha perdido a guarda da criança após um quadro de depressão pós-parto, em 2012. débora rolim da silv

========== TÓPICO 14 ==========

Documento 1:
corpo de marcelo rezende será velado na assembleia legislativa neste domingo. ele morreu vítima de falência múltipla dos órgãos em consequência de um câncer, informou o hospital moriah.. o corpo do jornalista marcelo rezende será velado neste domingo (17) na assembleia legislativa de são paulo. o sepultamento ainda não foi informado pela família. ele morreu, às 17h45 deste sábado (16), em são paulo, aos 65 anos, vítima de falência múltipla dos órgãos em consequência de um câncer, informou o hosp

Documento 2:
marcelo rezende morre aos 65 anos em são paulo. ele foi vítima de falência múltipla dos órgãos em consequência de um câncer, informou o hospital moriah.. o jornalista marcelo rezende morreu, às 17h45 deste sábado (16), em são paulo, aos 65 anos, vítima de falência múltipla dos órgãos em consequência de um câncer, informou o hospital moriah. rezende foi diagnosticado no início do ano com câncer no pâncreas com metástase no fígado. ele se afastou do comando do programa cidade alerta, da tv record,

========== TÓPICO 23 ==========

Documento 1:
dia mundial da água: veja programação do fórum mundial, em brasília, nesta quinta. evento prevê debates sobre o pantanal e a qualidade da água no mundo. data foi criada pela onu para pautar discussões sobre recursos hídricos.. no dia mundial da água, comemorado nesta quinta-feira (22), o fórum mundial em brasília vai propor o debate sobre recursos hídricos no mundo. em uma das primeiras sessões do dia, a organização das nações unidas (onu) idealizadora da data detalha dados divulgados no início

Documento 2:
população de valadaresmg sofre com a falta de água. prefeita petista diz que dilma não tem culpa. todo o abastecimento da cidade depende do rio doce, cujas águas, há mais de uma semana, deram lugar a uma lama espessa, com consistência que varia do leitoso ao argiloso.. a mineradora controlada pela vale e pela bhp não tem enviado água suficiente para a população, conforme determinado pelo plano de emergencial do município, apresentado no último dia 10. a enorme onda de resíduos químicos, vinda de

========== TÓPICO 28 ==========

Documento 1:
após avc, marisa letícia segue internada em uti sem previsão de alta. ex-primeira-dama deu entrada no hospital sírio-libanês, em são paulo, nesta terça-feira (24), com diagnóstico de acidente vascular cerebral.. a ex-primeira-dama marisa letícia, de 66 anos, mulher do ex-presidente luiz inácio lula da silva (pt), segue internada, nesta quarta-feira (25), na unidade de terapia intensiva (uti) do hospital sírio-libanês, no centro de são paulo, após ter sofrido um acidente vascular cerebral (avc) h

Documento 2:
após avc, marisa letícia segue internada em uti . ela está sedada e com a pressão intracraniana controlada.. a ex-primeira-dama marisa letícia, mulher do ex-presidente luiz inácio lula da silva, segue internada na unidade de terapia intensiva (uti) do hospital sírio-libanês, em são paulo, sem previsão de alta. ela sofreu um acidente vascular cerebral (avc) na terça-feira (23). ela está sedada e com a pressão intracraniana controlada, segundo o boletim médico divulgado às 12h05 desta quinta-feira

========== TÓPICO 35 ==========

Documento 1:
ue exige que brasil suspenda exportação de empresas envolvidas em fraude na operação carne fraca. china e coreia do sul também vão barrar compras, segundo agências. governo brasileiro e representações dos países ainda não se manifestaram. . a comissão europeia disse nesta segunda-feira (20) que está monitorando as importações de carne e exigiu que o brasil suspenda exportação de empresas envolvidas na operação carne fraca temporariamente. o nome de nenhuma empresa foi citado. a comissão garantir

Documento 2:
carne fraca: pf cumpre mandados em unidades da brf em mineiros e rio verde, em goiás. terceira fase da operação investiga fraudes em resultados de exames em amostras de processo industrial. ex-diretor-presidente da brf foi preso em são paulo.. a polícia federal cumpriu, nesta segunda-feira (5), dois mandados de busca e apreensão na unidade da brf brasil foods em rio verde e outro na fábrica de mineiros, na 3ª fase da operação carne fraca. também foi expedido um mandado de condução coercitiva, ou

========== TÓPICO 36 ==========

Documento 1:
complicou! novo vídeo cai na internet e mostra o cantor beto barbosa chamando policial de vagabundo. beto barbosa foi detido na manhã de hoje em fortaleza, ce. de acordo com informações do jornal tribuna do ceará , policiais deram voz de prisão, algemaram o músico e o encaminharam para a delegacia. em um vídeo feito no 2º distrito policial, beto demonstra sua indignação: o que foi que eu fiz? precisava ter me algemado. eu só disse que não era vagabundo a secretaria de segurança pública e defesa

Documento 2:
estudantes da ba rasgam outdoor de vereador que defende intervenção militar no brasil e político rebate: criminosos. placa publicitária destruída por alunos, uma das 4 instaladas pelo vereador em vitória da conquista, foi colocada nas proximidades da instituição de ensino.. estudantes da universidade estadual do sudoeste da bahia (uesb), em vitória da conquista, se revoltaram e rasgaram durante protesto um outdoor do vereador da cidade david salomão (ptc), que defende uma intervenção militar no

========== TÓPICO 43 ==========

Documento 1:
após 20 anos de rede globo, jornalista demitido abre o jogo: a globo não é dona do brasil. após 20 anos de emissora, sidney rezende, um dos jornalistas mais respeitados do país , esperou o fim de seu contrato com a rede globo, e resolveu quebrar o silêncio. sidney criticou a emissora durante a entrega do prêmio melhores do carnaval, no rio. ele pegou o microfone e protestou contra o monopólio da emissora. a globo não é dona do brasil, a globo não é dona do futebol e a globo não é dona do carnava

Documento 2:
sedenta por audiência, globo tentou transmitir coletiva de cunha e deu com os burros nágua. eduardo cunha, presidente afastado da câmara realizou uma coletiva hoje 21 através do canal tv câmara. o canal a cabo globonews do grupo globo avisou os assinantes que começaria a mostrar a coletiva: já temos imagens ao vivo da coletiva... , indicou uma das apresentadoras de um telejornal. a coletiva de cunha ficou menos de cinco minutos no ar. a globonews decidiu cortar a transmissão sem a menor explicaç

========== TÓPICO 46 ==========

Documento 1:
dr. richard l. day: a cura do câncer existe há décadas e está em poder dos rockefeller. . o dr. day era um médico eminente, professor de pediatria na mount sinai school of medicine (em manhattan) e diretor médico da organização planned parenthood. ele foi descrito como um membro da ordem dos bárbaros (que é um grupo de elite comprometido com a nova ordem mundial). durante uma palestra fechada para outros médicos em 1969, o dr. day disse que a cura para o câncer foi arquivada no rockefeller insti

Documento 2:
6 maneiras positivas de superar o medo da morte. . é neste ponto que devemos olhar para trás e contar nossas bênçãos e vitórias. criamos uma comunidade de amigos, parentes e colegas que se estendem há décadas. a maioria de nós vive entusiasmada com as muitas décadas de vida que ainda podemos ter décadas que queremos preencher com paixões, pessoas e lugares que nos interessam. quando chegamos na casa dos enta (50,60) é comum começar a se preocupar com nossa mortalidade. muitos de nós começamos a

========== TÓPICO 54 ==========

Documento 1:
retrospectiva 2017: os principais fatos do ano na região de piracicaba. bebê encontrado em mala, cão que fez vigília e encontrou família de morador de rua, quatro feminicídios foram algumas das notícias de maior destaque na região.. casos de violência contra a mulher, erro médico, assaltos a bancos, sonhos realizados, reencontros emocionantes, polêmicas e solidariedade estão entre os assuntos que marcaram 2017 na região de piracicaba (sp). o g1 listou algumas notícias publicadas entre janeiro e

Documento 2:
retrospectiva 2017: os principais fatos do ano no amapá. operações da pf, assalto ao vivo pelas redes sociais, ponte binacional, polícia que mais mata, recorde de quebra-cabeça, parto nas alturas são alguns dos fatos marcantes do ano. . operações da polícia federal, casos de violência, deputado preso, corais inéditos e bons exemplos estão entre as reportagens marcantes do ano no amapá . o g1 listou notícias publicadas entre janeiro e dezembro deste ano, em ordem cronológica, que chamaram a atenç

========== TÓPICO 63 ==========

Documento 1:
como é possível governar pagando uma quadrilha?, diz filósofo italiano. para antonio negri, a experiência petista se exauriu, mas o professor diz que não ser possível governar o país sem a herança de lula. antes de se tornar uma das mais importantes vozes críticas da esquerda mundial, o filósofo italiano antonio negri, de 84 anos, passou quatro anos e meio preso sob a acusação de participar da morte do líder democrata-cristã aldo moro. eram o fim dos anos 1970, anos de chumbo na itália. saiu da

Documento 2:
a face humana da sociologia. o pensador polonês zygmunt bauman reflete sobre a sociedade contemporânea e o desafio de encontrar respostas a problemas que ela mesma criou. o polonês zygmunt bauman, com a sabedoria extra que os 85 anos de vida lhe conferem, cultiva a virtude da dedicação, a despeito das distrações temporárias. e ao cultivar tal virtude, torna evidente seu apego ao campo de estudos que abraçou há muito tempo: é um sociólogo em tempo integral. acredita que suas ferramentas de anális

========== TÓPICO 68 ==========

Documento 1:
deputado tiririca passa mal após show e recebe atendimento em upa no ceará ele já recebeu alta e passa bem, diz unidade de pronto de atendimento. o humorista e deputado federal tiririca (pr-sp) passou mal após um show em camocim, no litoral do ceará, e foi socorrido na unidade de pronto atendimento (upa) da cidade, na manhã desta sexta-feira (5). de acordo com a unidade, tiririca deu entrada por volta das 8h desta sexta; ele recebeu atendimento da equipe médica e teve alta por volta do meio-dia.

Documento 2:
quadro clínico de resende se agrava ele teve falência em alguns órgãos, informa jornalista. . na noite de ontem (14) o jornalista da rede tv, vladimir alves, informou que o apresentador marcelo rezende, teve piora em seu quadro clínico e apresenta falência em alguns órgãos: após avaliação, em decorrência das complicações de um câncer no pâncreas que posteriormente irradiou para o fígado, o quadro de resende agravou e o apresentador foi diagnosticado com pneumonia grave. o câncer já comprometeu o

========== TÓPICO 70 ==========

Documento 1:
prefeitura de sp flexibiliza futuras regras para motoristas de aplicativos às vésperas do início da vigência das novas regras para aplicativos de transporte em são paulo, a gestão joão doria (psdb) decidiu flexibilizar nesta sexta-feira (5) alguns pontos da regulação e adiou o prazo para que motoristas e aplicativos se preparem antes de serem fiscalizados. as regras entram em vigor na próxima quarta-feira (10) e terão duas semanas para adaptação, sem aplicação de multas. até o início deste ano,

Documento 2:
temer avisa que vai vetar a lei anti-uber. mesmo com a aprovação dos deputados federais a lei que dificulta o trabalho do uber no brasil poderá ser vetada pelo presidente michel temer. a equipe do presidente michel temer diz esperar que as emendas consideradas prejudiciais ao serviço de transporte uber empresa que conecta motoristas particulares a passageiros e similares sejam alteradas ou derrubadas pela base aliada no senado. texto aprovado nesta terça-feira (4) na câmara dos deputados aproxim

========== TÓPICO 73 ==========

Documento 1:
deputado chora ao comentar reforma da previdência: é triste! penso nos pobres e isso me dói o coração. um texto que viralizou nas redes sociais mostra o cantor e deputado federal sérgio reis (77 anos) desabafando sobre a reforma da previdência. tentamos contato (através de email) com o gabinete do deputado em brasília para verificar a autenticidade do artigo, porém não obtivemos resposta até o momento. como o texto tem um viés positivo e passa uma mensagem de apoio aos aposentados, resolvemos pu

Documento 2:
segunda-feira, 5 de fevereiro de 2018. boa noite! aqui estão as principais notícias para você terminar o dia bem-informado. após 45 dias de recesso, começou o ano do congresso nacional - embora haja uma nova interrupção com o feriado de carnaval em alguns dias. as atenções estarão voltadas para a tentativa do governo de aprovar a reforma da previdência. o presidente michel temer não esteve presente na abertura dos trabalhos, mas mandou uma mensagem em que pede urgência no assunto da reforma. o p

In [86]:
dados_topicos = []

for topic in topic_info['Topic']:
    palavras = topic_model.get_topic(topic)

    palavras_str = ', '.join([
        palavra for palavra, peso in palavras[:10]
    ])

    docs = topic_model.get_representative_docs(topic)

    exemplo = docs[0][:500] if docs else ''

    dados_topicos.append({
        'topico': topic,
        'palavras': palavras_str,
        'exemplo': exemplo
    })

df_topicos = pd.DataFrame(dados_topicos)

df_topicos.head()

,topico,palavras,exemplo
0,0,"brasil, país, presidente, lula, brasileiros, brasileiro, temer, política, governo, brasileira","a defesa de aécio neves exigiu que o stf afaste edson fachin da relatoria do processo que o afasta do senado. nunca o samba do crioulo doido foi tão atual como no brasil hoje, como lembra eliane cantanhêde na coluna no estadão. nesta nau dos insensatos, a defesa escolhe o juiz de acordo com as conveniências do réu e o fato de ele já ter delinquido em outra ocasião o autoriza a fazê-lo. quanto mais diversas forem as causas contra o acusado mais ele se acha no direito de se livrar de quem o co..."
1,1,"norte, coreia, coreia norte, kim, eua, nuclear, un, trump, coréia, sul","coreia do norte alerta países: não se juntem a ações dos eua e estarão a salvo. vice-embaixador disse que país não irá colocar armas nucleares na mesa de negociação até que política hostil e ameaça dos eua sejam erradicadas. nações unidas - a coreia do norte alertou os países nesta segunda-feira, 16, na organização das nações unidas (onu) para que não se juntem aos estados unidos em ações militares contra o regime de kim jong-un e, assim, estarão a salvo de retaliação. o alerta estava contid..."
2,2,"bilhões, governo, ano, milhões, 2017, trabalho, feira, mil, mercado, empresas","saiba como foi a semana na economia. redução da taxa básica de juros, resultado do pib e acordo de leniência firmado pela jbs foram destaques. conforme esperado pelos economistas, o banco central reduziu a selic, a taxa básica de juros, em 1 ponto porcentual. outro resultado esperado era do produto interno bruto (pib) do brasil, que registrou alta após oito trimestres no vermelho. confira a seguir um resumo dos acontecimentos mais relevantes dos últimos dias. pib sobe 1 no 1º trimestre o pro..."
3,3,"odebrecht, milhões, dinheiro, delação, ex, propina, campanha, lula, mil, dilma","delação de ex-diretor da odebrecht atinge temer e cúpula do pmdb. cláudio melo filho disse que o presidente pediu, em 2014, r 10 milhões ao empreiteiro marcelo odebrecht. presidência disse repudiar delação.. no acordo de delação premiada, o ex-diretor de relações institucionais da odebrechet cláudio melo filho dedica um capítulo ao relacionamento que tinha com o presidente michel temer. os relatos fazem parte de um depoimento de 82 páginas que ele deu ao ministério público, no qual fala sobr..."
4,4,"dilma, impeachment, presidente, rousseff, dilma rousseff, senado, presidente dilma, câmara, presidenta, pt","dilma sabia da decisão irresponsável do deputado waldir maranhão. é tudo conversa fiada. durante pronunciamento feito hoje, a presidente dilma rousseff pediu a petistas e aliados que não se precipitassem diante da decisão do waldir maranhão (pp-ma), que monocraticamente anulou a sessão de votação do ipmeachment, ocorrida na câmara josé eduardo cardozo pediu ao presidente em exercício da câmara waldir maranhão para que a petista não descesse a rampa. dilma disse, diante da platéia, que o bras..."

In [87]:
pd.set_option('display.max_colwidth', 500)

df_topicos

,topico,palavras,exemplo
0,0,"brasil, país, presidente, lula, brasileiros, brasileiro, temer, política, governo, brasileira","a defesa de aécio neves exigiu que o stf afaste edson fachin da relatoria do processo que o afasta do senado. nunca o samba do crioulo doido foi tão atual como no brasil hoje, como lembra eliane cantanhêde na coluna no estadão. nesta nau dos insensatos, a defesa escolhe o juiz de acordo com as conveniências do réu e o fato de ele já ter delinquido em outra ocasião o autoriza a fazê-lo. quanto mais diversas forem as causas contra o acusado mais ele se acha no direito de se livrar de quem o co..."
1,1,"norte, coreia, coreia norte, kim, eua, nuclear, un, trump, coréia, sul","coreia do norte alerta países: não se juntem a ações dos eua e estarão a salvo. vice-embaixador disse que país não irá colocar armas nucleares na mesa de negociação até que política hostil e ameaça dos eua sejam erradicadas. nações unidas - a coreia do norte alertou os países nesta segunda-feira, 16, na organização das nações unidas (onu) para que não se juntem aos estados unidos em ações militares contra o regime de kim jong-un e, assim, estarão a salvo de retaliação. o alerta estava contid..."
2,2,"bilhões, governo, ano, milhões, 2017, trabalho, feira, mil, mercado, empresas","saiba como foi a semana na economia. redução da taxa básica de juros, resultado do pib e acordo de leniência firmado pela jbs foram destaques. conforme esperado pelos economistas, o banco central reduziu a selic, a taxa básica de juros, em 1 ponto porcentual. outro resultado esperado era do produto interno bruto (pib) do brasil, que registrou alta após oito trimestres no vermelho. confira a seguir um resumo dos acontecimentos mais relevantes dos últimos dias. pib sobe 1 no 1º trimestre o pro..."
3,3,"odebrecht, milhões, dinheiro, delação, ex, propina, campanha, lula, mil, dilma","delação de ex-diretor da odebrecht atinge temer e cúpula do pmdb. cláudio melo filho disse que o presidente pediu, em 2014, r 10 milhões ao empreiteiro marcelo odebrecht. presidência disse repudiar delação.. no acordo de delação premiada, o ex-diretor de relações institucionais da odebrechet cláudio melo filho dedica um capítulo ao relacionamento que tinha com o presidente michel temer. os relatos fazem parte de um depoimento de 82 páginas que ele deu ao ministério público, no qual fala sobr..."
4,4,"dilma, impeachment, presidente, rousseff, dilma rousseff, senado, presidente dilma, câmara, presidenta, pt","dilma sabia da decisão irresponsável do deputado waldir maranhão. é tudo conversa fiada. durante pronunciamento feito hoje, a presidente dilma rousseff pediu a petistas e aliados que não se precipitassem diante da decisão do waldir maranhão (pp-ma), que monocraticamente anulou a sessão de votação do ipmeachment, ocorrida na câmara josé eduardo cardozo pediu ao presidente em exercício da câmara waldir maranhão para que a petista não descesse a rampa. dilma disse, diante da platéia, que o bras..."
...,...,...,...
69,69,"internet, banda larga, larga, hackers, banda, anatel, 5g, fixa, vivo, empresa","internet limitada: 12 horas de netflix ou alguns dias no facebook já seriam suficiente para bloquear sua internet. com uso de internet cada vez mais se espalhando pelo território nacional, a verdade é que você deve se preocupar com tudo isso ... e muito!. algo que tem preocupado muita gente nas últimas semanas é o fato de que a internet deixará de ser ilimitada. o pânico começou quando a vivo colocou limites de consumo nos de banda larga fixa. e a anatel, ao contrário dos consumidores, viu a..."
70,70,"aplicativos, uber, caminhoneiros, transporte, motoristas, texto, taxistas, emendas, estradas, multa","prefeitura de sp flexibiliza futuras regras para motoristas de aplicativos às vésperas do início da vigência das novas regras para aplicativos de transporte em são paulo, a gestão joão doria (psdb) decidiu flexibilizar nesta sexta-feira (5) alguns pontos da regulação e adiou o prazo para que motoristas e aplicativos se preparem antes de serem fiscalizados. as regras entram em vigor na próxima quarta-feira (10) e terão duas semanas para adaptação, sem aplicação de multas. até o início deste a..."
71,71,"pf, diretor geral, daiello, diretor, novo diretor, jungmann, novo, galloro, segóvia, delegado","delegado fernando segóvia assumirá comando da pf no lugar de leandro daiello. daiello estava no cargo desde 2011 e comandou a pf durante a operação lava jato. segóvia tem 22 anos de carreira e foi superintendente da polícia federal no maranhão.. o presidente michel temer decidiu nomear o delegado fernando segóvia para diretor-geral da polícia federal no lugar de leandro daiello ( leia nota ao final desta reportagem ). nesta quarta-feira (8), o presidente, segóvia e o ministro da justiça, tor..."
72,72,"prefeito, doria, vereadores, crivella, promessas, câmara, municipal, greca, câmara vereadores, vereadores rio","doria deixa promessas de campanha de fora do plano de metas. prefeito prometeu zerar fila das vagas em creche em um ano, mas documento diz que meta é aumentar oferta de vagas em 30.. o prefeito joão doria (psdb) entregou o plano de metas , com as ações que irão nortear seu mandato até o fim da gestão, mas deixou de fora as promessas feitas durante sua campanha eleitoral. um dos itens mais polêmicos é na área de educação, já que a meta contradiz o próprio compromisso do tucano. veja as 50 met..."
73,73,"aposentadoria, idade, reforma, idade mínima, previdência, mínima, principais, governo, saque, pispasep","deputado chora ao comentar reforma da previdência: é triste! penso nos pobres e isso me dói o coração. um texto que viralizou nas redes sociais mostra o cantor e deputado federal sérgio reis (77 anos) desabafando sobre a reforma da previdência. tentamos contato (através de email) com o gabinete do deputado em brasília para verificar a autenticidade do artigo, porém não obtivemos resposta até o momento. como o texto tem um viés positivo e passa uma mensagem de apoio aos aposentados, resolvemo..."

In [88]:
df['topico_bertopic'] = topics

In [89]:
df['tema'] = df['topico_bertopic'].map(mapa_temas)

In [90]:
df[['id', 'label', 'topico_bertopic', 'tema']].head(20)

    id  label  topico_bertopic           tema
0    1  falso               28          Saúde
1    2  falso                0       Política
2    3  falso               55       Política
3    4  falso                3      Corrupção
4    5  falso               12       Política
5    6  falso                6       Política
6    7  falso                8       Religião
7    8  falso               16       Política
8    9  falso                4       Política
9   10  falso               53  Internacional
10  11  falso               13       Política
11  12  falso               21      Segurança
12  13  falso                4       Política
13  14  falso               21      Segurança
14  15  falso               10      Acidentes
15  16  falso                2       Economia
16  17  falso                4       Política
17  18  falso               34       Política
18  19  falso               40       Política
19  20  falso                6       Política

In [91]:
df['tema'].value_counts()

tema
Política          3285
Segurança          625
Corrupção          568
Internacional      530
Economia           404
Entretenimento     319
Saúde              233
Sociedade          206
Cultura            180
Religião           151
Acidentes          145
Mídia              116
Esportes           100
Meio Ambiente       80
Tecnologia          71
Alimentação         51
Ciência             51
Educação            42
Transportes         22
Animais             20
Name: count, dtype: int64

In [127]:
topicos_finais = new_topics

In [129]:
new_topics = topic_model.reduce_outliers(
    documentos,
    topics,
    strategy="embeddings",
    embeddings=embeddings
)

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [130]:
from collections import Counter

contagem = Counter(new_topics)

print("Total de textos:", len(new_topics))
print("Outliers restantes:", contagem[-1])

Total de textos: 7199
Outliers restantes: 0

In [131]:
print("Outliers antes:", topics.count(-1))
print("Outliers depois:", new_topics.count(-1))

Outliers antes: 0
Outliers depois: 0

In [132]:
outliers = new_topics.count(-1)
total = len(new_topics)

print(f"Outliers restantes: {outliers}")
print(f"Percentual: {outliers / total * 100:.2f}%")

Outliers restantes: 0
Percentual: 0.00%

In [133]:
df['topico_bertopic'] = topics
df['tema'] = df['topico_bertopic'].map(mapa_temas)

df['tema'].value_counts()

tema
Política          3285
Segurança          625
Corrupção          568
Internacional      530
Economia           404
Entretenimento     319
Saúde              233
Sociedade          206
Cultura            180
Religião           151
Acidentes          145
Mídia              116
Esportes           100
Meio Ambiente       80
Tecnologia          71
Alimentação         51
Ciência             51
Educação            42
Transportes         22
Animais             20
Name: count, dtype: int64

In [134]:
df['tema'].value_counts(normalize=True).mul(100).round(2)

tema
Política          45.63
Segurança          8.68
Corrupção          7.89
Internacional      7.36
Economia           5.61
Entretenimento     4.43
Saúde              3.24
Sociedade          2.86
Cultura            2.50
Religião           2.10
Acidentes          2.01
Mídia              1.61
Esportes           1.39
Meio Ambiente      1.11
Tecnologia         0.99
Alimentação        0.71
Ciência            0.71
Educação           0.58
Transportes        0.31
Animais            0.28
Name: proportion, dtype: float64

In [135]:
print("Total de textos:", len(df))
print("Sem tema:", df['tema'].isna().sum())

Total de textos: 7199
Sem tema: 0

In [136]:
comparacao = pd.DataFrame({
    'topico_original': topics,
    'topico_final': new_topics
})

# Mostrar apenas os que mudaram
mudaram = comparacao[
    comparacao['topico_original'] != comparacao['topico_final']
]

print("Textos redistribuídos:", len(mudaram))

Textos redistribuídos: 0

In [137]:
df['topico_bertopic'].value_counts().sort_index()

topico_bertopic
0     591
1     347
2     315
3     368
4     245
     ...
69     34
70     22
71     26
72     22
73     24
Name: count, Length: 74, dtype: int64

In [138]:
topic_info_final = topic_model.get_topic_info()

topic_info_final[['Topic', 'Count', 'Name']]

    Topic  Count                                          Name
0      -1   2647                 -1_lula_presidente_ex_federal
1       0    363                 0_brasil_país_presidente_lula
2       1    346               1_norte_coreia_coreia norte_kim
3       2    266                 2_bilhões_governo_ano_milhões
4       3    261          3_odebrecht_milhões_dinheiro_delação
..    ...    ...                                           ...
70     69     16         69_internet_banda larga_larga_hackers
71     70     15  70_aplicativos_uber_caminhoneiros_transporte
72     71     15           71_pf_diretor geral_daiello_diretor
73     72     15         72_prefeito_doria_vereadores_crivella
74     73     15   73_aposentadoria_idade_reforma_idade mínima

[75 rows x 3 columns]

In [140]:
df = df[
    ['id', 'label', 'arquivo', 'texto_original',
     'texto_preprocessado', 'topico_bertopic', 'tema']
]

In [141]:
df.columns

Index(['id', 'label', 'arquivo', 'texto_original', 'texto_preprocessado',
       'topico_bertopic', 'tema'],
      dtype='object')

In [142]:
df[['texto_original', 'topico_bertopic', 'tema']].sample(10)

,texto_original,topico_bertopic,tema
2656,"Brasília contrata fundação espírita que incorpora Galileu e Abraham Lincoln para controlar escassez de água. Não [...] não é uma piada! A informação é da jornalista Cleo Guimarães, do Globo. Correndo um risco real de ""secar"" literalmente, ou seja, passar por um desabastecimento de água, a cidade de Brasília resolveu inovar. A Capital Federal contratou a Cacique Cobra Coral, uma fundação exotérica que diz ""ter poder"" de controlar o tempo. No site da Cobra Coral, a explicação é a seguinte: ...",23,Meio Ambiente
2404,"Próxima manifestação terá R$ 300 de ajuda de custo e 20 pães com mortadela para cada petista. O PT é hilário [...] o PT é sujo [...] o PT é desonesto [...] o PT é rico [...] enfim, o PT já era!. O cartaz divulgado pelo SINTE/SC (Sindicato dos Trabalhadores em Educação na Rede Pública do Ensino do Estado de Santa Catarina) com o apoio da CUT mostra que o PT está gastando até o último centavo para tentar se manter no poder. Para tentar defender o indefensável , um grupo disfarçado de ""FOR...",12,Política
2625,"Meses após polêmica sobre ""suposta"" agressão, Victor Chaves e Poliana Bagatini se separam. O cantor apareceu sem aliança durante uma apresentação no teatro Tom Brasil, em São Paulo. Mas não foi só isso ... Léo, parceiro de Victor, deixou escapar uma dica durante a apresentação da dupla. Em determinado momento, Léo declarou para a platéia:\n",15,Entretenimento
655,"República Bolivariana da ""Brazuela"" aciona facebook e Zuckerberg recua em crítica ao governo brasileiro. Às vezes fico na dúvida se estamos sob o comando de Dilma Rousseff ou de Nicolás Maduro [...] ou até mesmo de Evo Morales. (Patrícia Carvalho para o Diário do Brasil) Acredite se quiser ... O Palácio do Planalto parece que não digeriu uma postagem do criador do facebook Mark Zuckerberg estimulando os brasileiros a reagirem contra o bloqueio do aplicativo WhatsApp, No post, Mark dizia ...",0,Política
4416,"Senadora Gleisi Hoffmann toma posse oficialmente como presidente do PT. Ré na Lava Jato, parlamentar foi eleita no mês passado em convenção nacional. Demais integrantes do diretório nacional petista também tomaram posse para os próximos dois anos. . A senadora Gleisi Hoffmann (PR) tomou posse oficialmente como presidente nacional do PT nesta quarta-feira (5) em Brasília. Ela ficará à frente da legenda até 2019 ( saiba mais abaixo como foram os discursos de Gleisi, Lula e Dilma no evento ). T...",7,Política
5758,"A Polícia Federal analisa as gravações apresentadas pelo ex-ministro Marcelo Calero como prova de que foi pressionado por integrantes do governo Temer a tomar uma decisão que favorecia interesses pessoais do agora ex-ministro Geddel Vieira Lima. Calero informou à PF que gravou o presidente Michel Temer, os ministros Eliseu Padilha (Casa Civil) e Geddel, além de outros servidores do Planalto. Ele entregou para a PF esses áudios que comprovariam suas acusações. Em depoimento à \n",21,Segurança
6317,"O ex-presidente Fernando Henrique Cardoso disse nesta terça-feira, 12, que a Força Aérea Brasileira (FAB) já tinha preferência pelos caças Gripen, fabricados pela multinacional sueca Saab, em 2002, ao fim de seu governo. Em depoimento por videoconferência à 10.ª Vara da Justiça Federal em Brasília, ele explicou que a opção da Aeronáutica foi-lhe manifestada numa reunião, mas que ele preferiu não comprar as aeronaves de defesa naquele momento para não “onerar” a gestão do sucessor, que viria ...",10,Acidentes
2532,"Lula não se conforma e diz que foi traído pelo deputado palhaço. O jornal O Tempo publicou uma notícia no mínimo curiosa. Durante algumas horas, em uma manhã de domingo, o hotel Golden Tulip (em Brasília) se tornou um picadeiro e promoveu um encontro de ""ícones circenses"" Lula comentou com Dilma que havia recebido o palhaço Tiririca em sua suíte de hotel, ou seja, em seu gabinete clandestino onde tentava comprar votos para tentar salvar Dilma. ""Ele esteve comigo hoje. Como ele faz isso...",13,Política
2760,"Eduardo Costa sobre exposição do MAM: ""Uma desgraça. Parece que o capeta resolveu ensinar arte"". Quando se trata de temas polêmicos, o cantor sertanejo Eduardo não foge da briga!. Mesmo sendo criticado (pela turma do mimimi) nas redes sociais, o sertanejo fez questão de expor sua opinião sobre a exposição sem vergonha que ocorreu no MAM (Museu de Arte Moderna) se São Paulo: "" Será arte ou será Jesus voltando? Parece que o capeta tá morando no museu de arte de São Paulo e resolveu ensinar a...",29,Cultura
3285,"Marca de sabão em pó faz publicidade de gênero para crianças e 98% dos internautas desaprovam. Uma grande marca de sabão em pó, ao invés de continuar vendendo sabão em pó , quis meter o nariz onde não foi chamada. A OMO lançou um ""comunicado urgente"" para pais e mães. Em sua página do Facebook e também no Youtube , a marca convocou todos aqueles que tem filhos ""a fazerem recall de todas as brincadeiras que reforcem clichês sobre gênero."" Ou seja, é um modo disfarçado de ""impor"" questões de...",29,Cultura

In [143]:
df['tema'].value_counts()

tema
Política          3285
Segurança          625
Corrupção          568
Internacional      530
Economia           404
Entretenimento     319
Saúde              233
Sociedade          206
Cultura            180
Religião           151
Acidentes          145
Mídia              116
Esportes           100
Meio Ambiente       80
Tecnologia          71
Alimentação         51
Ciência             51
Educação            42
Transportes         22
Animais             20
Name: count, dtype: int64

In [144]:
df.to_csv(
    'dataset_topics.csv',
    index=False,
    encoding='utf-8-sig'
)

In [148]:
import os
print(os.path.exists('dataset_topics.csv'))

True

In [149]:
df_salvo = pd.read_csv(
    'dataset_topics.csv',
    encoding='utf-8-sig'
)

print(df_salvo.shape)
print(df_salvo.columns)

(7199, 7)
Index(['id', 'label', 'arquivo', 'texto_original', 'texto_preprocessado',
       'topico_bertopic', 'tema'],
      dtype='object')